"""fleet and equipment

Revision ID: 01653f2984a2
Revises: 11ce6371153f
Create Date: 2026-08-30 22:42:38.703267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '01653f2984a2'
down_revision: Union[str, None] = '11ce6371153f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('excavator', 'loader', 'grader', 'roller', 'tipper', 'truck', 'crane', 'generator', 'pump', 'compressor', 'light_vehicle', 'other', name='equipment_category'), nullable=False),
    sa.Column('make', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('registration', sa.String(length=30), nullable=True),
    sa.Column('serial_number', sa.String(length=60), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('ownership', sa.Enum('owned', 'hired', name='ownership'), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('available', 'on_site', 'workshop', 'standing', 'off_hired', 'disposed', name='equipment_status'), nullable=False),
    sa.Column('current_project_id', sa.UUID(), nullable=True),
    sa.Column('meter_type', sa.Enum('hours', 'kilometres', name='meter_type'), nullable=False),
    sa.Column('current_meter', sa.Numeric(precision=12, scale=1), nullable=False),
    sa.Column('expected_burn_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_equipment_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['current_project_id'], ['projects.id'], name=op.f('fk_equipment_current_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_equipment_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment'))
    )
    op.create_index(op.f('ix_equipment_category'), 'equipment', ['category'], unique=False)
    op.create_index(op.f('ix_equipment_code'), 'equipment', ['code'], unique=True)
    op.create_index(op.f('ix_equipment_current_project_id'), 'equipment', ['current_project_id'], unique=False)
    op.create_index(op.f('ix_equipment_registration'), 'equipment', ['registration'], unique=False)
    op.create_index(op.f('ix_equipment_status'), 'equipment', ['status'], unique=False)
    op.create_index(op.f('ix_equipment_supplier_id'), 'equipment', ['supplier_id'], unique=False)
    op.create_table('equipment_assignments',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_equipment_assignments_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_equipment_assignments_equipment_id_equipment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_equipment_assignments_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_assignments'))
    )
    op.create_index(op.f('ix_equipment_assignments_equipment_id'), 'equipment_assignments', ['equipment_id'], unique=False)
    op.create_index('ix_equipment_assignments_open', 'equipment_assignments', ['equipment_id', 'ended_on'], unique=False)
    op.create_index(op.f('ix_equipment_assignments_project_id'), 'equipment_assignments', ['project_id'], unique=False)
    op.create_table('fuel_logs',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('litres', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meter', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('stock_item_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('operator', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_fuel_logs_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_fuel_logs_equipment_id_equipment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_fuel_logs_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], name=op.f('fk_fuel_logs_stock_item_id_stock_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fuel_logs'))
    )
    op.create_index('ix_fuel_logs_equipment_date', 'fuel_logs', ['equipment_id', 'log_date'], unique=False)
    op.create_index(op.f('ix_fuel_logs_equipment_id'), 'fuel_logs', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_fuel_logs_log_date'), 'fuel_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_fuel_logs_project_id'), 'fuel_logs', ['project_id'], unique=False)
    op.create_table('maintenance_schedules',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('interval_meter', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('last_done_meter', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('last_done_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_maintenance_schedules_equipment_id_equipment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_schedules'))
    )
    op.create_index(op.f('ix_maintenance_schedules_equipment_id'), 'maintenance_schedules', ['equipment_id'], unique=False)
    op.create_table('meter_readings',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('meter', sa.Numeric(precision=12, scale=1), nullable=False),
    sa.Column('source', sa.Enum('manual', 'telematics', name='meter_source'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('idle_hours', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_meter_readings_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_meter_readings_equipment_id_equipment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_meter_readings_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meter_readings'))
    )
    op.create_index('ix_meter_readings_equipment_date', 'meter_readings', ['equipment_id', 'reading_date'], unique=False)
    op.create_index(op.f('ix_meter_readings_equipment_id'), 'meter_readings', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_meter_readings_project_id'), 'meter_readings', ['project_id'], unique=False)
    op.create_index(op.f('ix_meter_readings_reading_date'), 'meter_readings', ['reading_date'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('meter', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('downtime_hours', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_maintenance_records_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_maintenance_records_equipment_id_equipment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['maintenance_schedules.id'], name=op.f('fk_maintenance_records_schedule_id_maintenance_schedules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_maintenance_records_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_records'))
    )
    op.create_index(op.f('ix_maintenance_records_equipment_id'), 'maintenance_records', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_service_date'), 'maintenance_records', ['service_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_records_service_date'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_equipment_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_meter_readings_reading_date'), table_name='meter_readings')
    op.drop_index(op.f('ix_meter_readings_project_id'), table_name='meter_readings')
    op.drop_index(op.f('ix_meter_readings_equipment_id'), table_name='meter_readings')
    op.drop_index('ix_meter_readings_equipment_date', table_name='meter_readings')
    op.drop_table('meter_readings')
    op.drop_index(op.f('ix_maintenance_schedules_equipment_id'), table_name='maintenance_schedules')
    op.drop_table('maintenance_schedules')
    op.drop_index(op.f('ix_fuel_logs_project_id'), table_name='fuel_logs')
    op.drop_index(op.f('ix_fuel_logs_log_date'), table_name='fuel_logs')
    op.drop_index(op.f('ix_fuel_logs_equipment_id'), table_name='fuel_logs')
    op.drop_index('ix_fuel_logs_equipment_date', table_name='fuel_logs')
    op.drop_table('fuel_logs')
    op.drop_index(op.f('ix_equipment_assignments_project_id'), table_name='equipment_assignments')
    op.drop_index('ix_equipment_assignments_open', table_name='equipment_assignments')
    op.drop_index(op.f('ix_equipment_assignments_equipment_id'), table_name='equipment_assignments')
    op.drop_table('equipment_assignments')
    op.drop_index(op.f('ix_equipment_supplier_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_status'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_registration'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_current_project_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_code'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_category'), table_name='equipment')
    op.drop_table('equipment')
    # Dropping the tables leaves the types behind, and the next upgrade then
    # fails with "type already exists".
    for name in ('meter_source', 'meter_type', 'ownership',
                 'equipment_status', 'equipment_category'):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
