"""m8_requisitions

Revision ID: 0394c599d4f6
Revises: f025e429e554
Create Date: 2026-08-04 06:34:49.224402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0394c599d4f6'
down_revision: Union[str, None] = 'f025e429e554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requisitions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('doc_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('open', 'actioned', 'cancelled', name='requisition_status'), nullable=False),
    sa.Column('needed_by', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actioned_by', sa.UUID(), nullable=True),
    sa.Column('rfq_id', sa.UUID(), nullable=True),
    sa.Column('po_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['actioned_by'], ['users.id'], name=op.f('fk_requisitions_actioned_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_requisitions_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('fk_requisitions_po_id_purchase_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_requisitions_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], name=op.f('fk_requisitions_rfq_id_rfqs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requisitions')),
    sa.UniqueConstraint('doc_number', name=op.f('uq_requisitions_doc_number'))
    )
    op.create_index(op.f('ix_requisitions_project_id'), 'requisitions', ['project_id'], unique=False)
    op.create_table('requisition_items',
    sa.Column('requisition_id', sa.UUID(), nullable=False),
    sa.Column('boq_item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], name=op.f('fk_requisition_items_boq_item_id_boq_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], name=op.f('fk_requisition_items_requisition_id_requisitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requisition_items'))
    )
    op.create_index(op.f('ix_requisition_items_boq_item_id'), 'requisition_items', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_requisition_items_requisition_id'), 'requisition_items', ['requisition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requisition_items_requisition_id'), table_name='requisition_items')
    op.drop_index(op.f('ix_requisition_items_boq_item_id'), table_name='requisition_items')
    op.drop_table('requisition_items')
    op.drop_index(op.f('ix_requisitions_project_id'), table_name='requisitions')
    op.drop_table('requisitions')
    sa.Enum(name='requisition_status').drop(op.get_bind(), checkfirst=True)
