"""m12_admin_activity_invites

Revision ID: 0de77b679595
Revises: 3f9e6acac5bf
Create Date: 2026-08-04 18:08:46.042138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0de77b679595'
down_revision: Union[str, None] = '3f9e6acac5bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invites',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    # The user_role type already exists from the users table, so reuse it
    # rather than trying to create it a second time.
    sa.Column(
        'role',
        postgresql.ENUM(
            'admin', 'project_manager', 'site_manager', 'procurement_officer', 'viewer',
            name='user_role', create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_user_invites_invited_by_users'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_invites'))
    )
    op.create_index(op.f('ix_user_invites_email'), 'user_invites', ['email'], unique=False)
    op.create_index(op.f('ix_user_invites_token_hash'), 'user_invites', ['token_hash'], unique=True)
    op.create_table('activity_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('link_path', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index('ix_activity_logs_created', 'activity_logs', ['created_at'], unique=False)
    op.create_index('ix_activity_logs_entity', 'activity_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.alter_column('stock_items', 'tracking_mode',
               existing_type=postgresql.ENUM('none', 'batch', 'serial', name='tracking_mode'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_items', 'expiry_warning_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_items', 'expiry_warning_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               existing_nullable=False)
    op.alter_column('stock_items', 'tracking_mode',
               existing_type=postgresql.ENUM('none', 'batch', 'serial', name='tracking_mode'),
               server_default=sa.text("'none'::tracking_mode"),
               existing_nullable=False)
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index('ix_activity_logs_entity', table_name='activity_logs')
    op.drop_index('ix_activity_logs_created', table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_user_invites_token_hash'), table_name='user_invites')
    op.drop_index(op.f('ix_user_invites_email'), table_name='user_invites')
    op.drop_table('user_invites')
    # ### end Alembic commands ###
