"""bank reconciliation record

Revision ID: 11ce6371153f
Revises: b5ede1f20e57
Create Date: 2026-08-06 11:09:43.554508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '11ce6371153f'
down_revision: Union[str, None] = 'b5ede1f20e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_reconciliations',
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('statement_balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('book_balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('deposits_in_transit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('unpresented_payments', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('fk_bank_reconciliations_bank_account_id_bank_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_bank_reconciliations_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_reconciliations')),
    sa.UniqueConstraint('bank_account_id', 'statement_date', name=op.f('uq_bank_reconciliations_bank_account_id_statement_date'))
    )
    op.create_index(op.f('ix_bank_reconciliations_bank_account_id'), 'bank_reconciliations', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_reconciliations_statement_date'), 'bank_reconciliations', ['statement_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_reconciliations_statement_date'), table_name='bank_reconciliations')
    op.drop_index(op.f('ix_bank_reconciliations_bank_account_id'), table_name='bank_reconciliations')
    op.drop_table('bank_reconciliations')
    # ### end Alembic commands ###
