"""m2 procurement

Revision ID: 144352502f5b
Revises: 70dfb3054e40
Create Date: 2026-08-02 13:44:03.804028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '144352502f5b'
down_revision: Union[str, None] = '70dfb3054e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_id', sa.String(length=60), nullable=True),
    sa.Column('categories', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_suppliers_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('name', name=op.f('uq_suppliers_name'))
    )
    op.create_table('rfqs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('doc_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'closed', name='rfq_status'), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_rfqs_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_rfqs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rfqs')),
    sa.UniqueConstraint('doc_number', name=op.f('uq_rfqs_doc_number'))
    )
    op.create_index(op.f('ix_rfqs_project_id'), 'rfqs', ['project_id'], unique=False)
    op.create_table('quotes',
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('received', 'accepted', 'rejected', name='quote_status'), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('delivery_terms', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('ai_extracted', sa.Boolean(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_quotes_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], name=op.f('fk_quotes_rfq_id_rfqs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_quotes_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotes')),
    sa.UniqueConstraint('rfq_id', 'supplier_id', name=op.f('uq_quotes_rfq_id_supplier_id'))
    )
    op.create_index(op.f('ix_quotes_rfq_id'), 'quotes', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_quotes_supplier_id'), 'quotes', ['supplier_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('doc_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'received', 'cancelled', name='po_status'), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_purchase_orders_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_purchase_orders_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_purchase_orders_quote_id_quotes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_orders_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('doc_number', name=op.f('uq_purchase_orders_doc_number'))
    )
    op.create_index(op.f('ix_purchase_orders_project_id'), 'purchase_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('rfq_items',
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('boq_item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], name=op.f('fk_rfq_items_boq_item_id_boq_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], name=op.f('fk_rfq_items_rfq_id_rfqs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rfq_items')),
    sa.UniqueConstraint('rfq_id', 'boq_item_id', name=op.f('uq_rfq_items_rfq_id_boq_item_id'))
    )
    op.create_index(op.f('ix_rfq_items_boq_item_id'), 'rfq_items', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_rfq_items_rfq_id'), 'rfq_items', ['rfq_id'], unique=False)
    op.create_table('po_items',
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('boq_item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), sa.Computed('quantity * unit_price', persisted=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], name=op.f('fk_po_items_boq_item_id_boq_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('fk_po_items_po_id_purchase_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_po_items'))
    )
    op.create_index(op.f('ix_po_items_boq_item_id'), 'po_items', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_po_items_po_id'), 'po_items', ['po_id'], unique=False)
    op.create_table('quote_items',
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('rfq_item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), sa.Computed('quantity * unit_price', persisted=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_quote_items_quote_id_quotes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rfq_item_id'], ['rfq_items.id'], name=op.f('fk_quote_items_rfq_item_id_rfq_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_items')),
    sa.UniqueConstraint('quote_id', 'rfq_item_id', name=op.f('uq_quote_items_quote_id_rfq_item_id'))
    )
    op.create_index(op.f('ix_quote_items_quote_id'), 'quote_items', ['quote_id'], unique=False)
    op.create_index(op.f('ix_quote_items_rfq_item_id'), 'quote_items', ['rfq_item_id'], unique=False)
    # Fix M1 bug: created_at default was captured as a frozen literal timestamp
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_items_rfq_item_id'), table_name='quote_items')
    op.drop_index(op.f('ix_quote_items_quote_id'), table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_index(op.f('ix_po_items_po_id'), table_name='po_items')
    op.drop_index(op.f('ix_po_items_boq_item_id'), table_name='po_items')
    op.drop_table('po_items')
    op.drop_index(op.f('ix_rfq_items_rfq_id'), table_name='rfq_items')
    op.drop_index(op.f('ix_rfq_items_boq_item_id'), table_name='rfq_items')
    op.drop_table('rfq_items')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_project_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_quotes_supplier_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_rfq_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_rfqs_project_id'), table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
