"""task priority tags subtasks

Revision ID: 1464a2d194c8
Revises: 3143dd56a0ca
Create Date: 2026-08-05 08:05:45.279727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1464a2d194c8'
down_revision: Union[str, None] = '3143dd56a0ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # add_column does not emit CREATE TYPE, so the type has to exist first.
    priority = postgresql.ENUM(
        'low', 'normal', 'high', 'urgent', name='task_priority', create_type=False
    )
    priority.create(op.get_bind(), checkfirst=True)
    op.add_column('tasks', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('priority', priority, server_default='normal', nullable=False))
    op.add_column('tasks', sa.Column('tags', postgresql.ARRAY(sa.String(length=40)), server_default='{}', nullable=False))
    op.create_index(op.f('ix_tasks_parent_id'), 'tasks', ['parent_id'], unique=False)
    op.create_foreign_key(op.f('fk_tasks_parent_id_tasks'), 'tasks', 'tasks', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_parent_id_tasks'), 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_parent_id'), table_name='tasks')
    op.drop_column('tasks', 'tags')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'parent_id')
    # Dropping the column leaves the type behind, and the next upgrade then
    # fails with "type task_priority already exists".
    sa.Enum(name='task_priority').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
