"""m3 site expenses inventory

Revision ID: 2142af130047
Revises: 144352502f5b
Create Date: 2026-08-02 15:54:36.444637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2142af130047'
down_revision: Union[str, None] = '144352502f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # New ledger source for store issues (allowed in-transaction on PG12+;
    # the value is only added here, never used within this migration)
    op.execute("ALTER TYPE cost_source ADD VALUE IF NOT EXISTS 'inventory_issue'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_items',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('qty_on_hand', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stock_items_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_items')),
    sa.UniqueConstraint('code', name=op.f('uq_stock_items_code'))
    )
    op.create_table('site_diary_entries',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('weather', sa.Enum('sunny', 'cloudy', 'rain', 'storm', name='weather_condition'), nullable=False),
    sa.Column('labour_headcount', sa.Integer(), nullable=False),
    sa.Column('plant_equipment', sa.Text(), nullable=True),
    sa.Column('work_done', sa.Text(), nullable=False),
    sa.Column('delays', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_site_diary_entries_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_site_diary_entries_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_diary_entries')),
    sa.UniqueConstraint('project_id', 'entry_date', name=op.f('uq_site_diary_entries_project_id_entry_date'))
    )
    op.create_index(op.f('ix_site_diary_entries_project_id'), 'site_diary_entries', ['project_id'], unique=False)
    op.create_table('site_issues',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='issue_severity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', name='issue_status'), nullable=False),
    sa.Column('raised_date', sa.Date(), nullable=False),
    sa.Column('resolved_date', sa.Date(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_site_issues_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_site_issues_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_issues'))
    )
    op.create_index(op.f('ix_site_issues_project_id'), 'site_issues', ['project_id'], unique=False)
    op.create_index('ix_site_issues_project_status', 'site_issues', ['project_id', 'status'], unique=False)
    op.create_table('expense_claims',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('boq_item_id', sa.UUID(), nullable=True),
    sa.Column('doc_number', sa.String(length=20), nullable=False),
    sa.Column('category', sa.Enum('materials', 'transport', 'fuel', 'accommodation', 'meals', 'tools', 'other', name='expense_category'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='expense_status'), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('receipt_ref', sa.String(length=60), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('cost_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_expense_claims_approved_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], name=op.f('fk_expense_claims_boq_item_id_boq_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cost_entry_id'], ['cost_entries.id'], name=op.f('fk_expense_claims_cost_entry_id_cost_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_expense_claims_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_expense_claims_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_claims')),
    sa.UniqueConstraint('doc_number', name=op.f('uq_expense_claims_doc_number'))
    )
    op.create_index(op.f('ix_expense_claims_boq_item_id'), 'expense_claims', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_expense_claims_project_id'), 'expense_claims', ['project_id'], unique=False)
    op.create_index('ix_expense_claims_project_status', 'expense_claims', ['project_id', 'status'], unique=False)
    op.create_index('ix_expense_claims_status', 'expense_claims', ['status'], unique=False)
    op.create_table('stock_movements',
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('doc_number', sa.String(length=20), nullable=False),
    sa.Column('movement_type', sa.Enum('goods_in', 'issue', 'adjustment', name='stock_movement_type'), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('boq_item_id', sa.UUID(), nullable=True),
    sa.Column('cost_entry_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], name=op.f('fk_stock_movements_boq_item_id_boq_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cost_entry_id'], ['cost_entries.id'], name=op.f('fk_stock_movements_cost_entry_id_cost_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stock_movements_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_stock_movements_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], name=op.f('fk_stock_movements_stock_item_id_stock_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements')),
    sa.UniqueConstraint('doc_number', name=op.f('uq_stock_movements_doc_number'))
    )
    op.create_index('ix_stock_movements_item_date', 'stock_movements', ['stock_item_id', 'movement_date'], unique=False)
    op.create_index(op.f('ix_stock_movements_project_id'), 'stock_movements', ['project_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_stock_item_id'), 'stock_movements', ['stock_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Note: the 'inventory_issue' value added to cost_source cannot be removed
    # (PostgreSQL does not support dropping enum values); it is left in place.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_stock_item_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_project_id'), table_name='stock_movements')
    op.drop_index('ix_stock_movements_item_date', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index('ix_expense_claims_status', table_name='expense_claims')
    op.drop_index('ix_expense_claims_project_status', table_name='expense_claims')
    op.drop_index(op.f('ix_expense_claims_project_id'), table_name='expense_claims')
    op.drop_index(op.f('ix_expense_claims_boq_item_id'), table_name='expense_claims')
    op.drop_table('expense_claims')
    op.drop_index('ix_site_issues_project_status', table_name='site_issues')
    op.drop_index(op.f('ix_site_issues_project_id'), table_name='site_issues')
    op.drop_table('site_issues')
    op.drop_index(op.f('ix_site_diary_entries_project_id'), table_name='site_diary_entries')
    op.drop_table('site_diary_entries')
    op.drop_table('stock_items')
    # ### end Alembic commands ###
