"""comments and timesheet task link

Revision ID: 3143dd56a0ca
Revises: 7e5a0dc71fe2
Create Date: 2026-08-05 07:11:41.159204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3143dd56a0ca'
down_revision: Union[str, None] = '7e5a0dc71fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.String(length=120), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index('ix_comments_entity', 'comments', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_comments_entity_id'), 'comments', ['entity_id'], unique=False)
    op.add_column('timesheets', sa.Column('task_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_timesheets_task_id'), 'timesheets', ['task_id'], unique=False)
    op.create_foreign_key(op.f('fk_timesheets_task_id_tasks'), 'timesheets', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_timesheets_task_id_tasks'), 'timesheets', type_='foreignkey')
    op.drop_index(op.f('ix_timesheets_task_id'), table_name='timesheets')
    op.drop_column('timesheets', 'task_id')
    op.drop_index(op.f('ix_comments_entity_id'), table_name='comments')
    op.drop_index('ix_comments_entity', table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
