"""m11_multi_location

Revision ID: 3866c4b89855
Revises: 44331b258a92
Create Date: 2026-08-04 12:12:31.249424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3866c4b89855'
down_revision: Union[str, None] = '44331b258a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerate cannot see a new value on an existing enum, so it is added
    # by hand. Must run before any row can reference it.
    op.execute("ALTER TYPE stock_movement_type ADD VALUE IF NOT EXISTS 'transfer'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_locations',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('store', 'site', 'yard', name='stock_location_kind'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stock_locations_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_stock_locations_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_locations')),
    sa.UniqueConstraint('code', name=op.f('uq_stock_locations_code'))
    )
    op.create_index(op.f('ix_stock_locations_project_id'), 'stock_locations', ['project_id'], unique=False)
    op.create_table('stock_levels',
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], name=op.f('fk_stock_levels_location_id_stock_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], name=op.f('fk_stock_levels_stock_item_id_stock_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_levels')),
    sa.UniqueConstraint('stock_item_id', 'location_id', name=op.f('uq_stock_levels_stock_item_id_location_id'))
    )
    op.create_index(op.f('ix_stock_levels_location_id'), 'stock_levels', ['location_id'], unique=False)
    op.create_index(op.f('ix_stock_levels_stock_item_id'), 'stock_levels', ['stock_item_id'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('doc_number', sa.String(length=20), nullable=False),
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('from_location_id', sa.UUID(), nullable=False),
    sa.Column('to_location_id', sa.UUID(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stock_transfers_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['stock_locations.id'], name=op.f('fk_stock_transfers_from_location_id_stock_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], name=op.f('fk_stock_transfers_stock_item_id_stock_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_location_id'], ['stock_locations.id'], name=op.f('fk_stock_transfers_to_location_id_stock_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_transfers')),
    sa.UniqueConstraint('doc_number', name=op.f('uq_stock_transfers_doc_number'))
    )
    op.create_index(op.f('ix_stock_transfers_from_location_id'), 'stock_transfers', ['from_location_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_stock_item_id'), 'stock_transfers', ['stock_item_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_to_location_id'), 'stock_transfers', ['to_location_id'], unique=False)
    op.add_column('stock_movements', sa.Column('location_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_stock_movements_location_id'), 'stock_movements', ['location_id'], unique=False)

    # --- Move the existing single-store world into a real location ---------
    # Every current item and every historical movement belongs to one default
    # store, so nothing is orphaned and single-store users see no change.
    op.execute(
        """
        INSERT INTO stock_locations
            (id, code, name, kind, is_default, is_active, created_at, updated_at)
        VALUES
            (gen_random_uuid(), 'MAIN', 'Main Store', 'store', true, true, now(), now())
        """
    )
    op.execute(
        """
        INSERT INTO stock_levels
            (id, stock_item_id, location_id, quantity, created_at, updated_at)
        SELECT gen_random_uuid(), si.id, loc.id, si.qty_on_hand, now(), now()
        FROM stock_items si
        CROSS JOIN (SELECT id FROM stock_locations WHERE is_default) loc
        """
    )
    op.execute(
        """
        UPDATE stock_movements
        SET location_id = (SELECT id FROM stock_locations WHERE is_default)
        WHERE location_id IS NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_location_id'), table_name='stock_movements')
    op.drop_column('stock_movements', 'location_id')
    op.drop_index(op.f('ix_stock_transfers_to_location_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_stock_item_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_from_location_id'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.drop_index(op.f('ix_stock_levels_stock_item_id'), table_name='stock_levels')
    op.drop_index(op.f('ix_stock_levels_location_id'), table_name='stock_levels')
    op.drop_table('stock_levels')
    op.drop_index(op.f('ix_stock_locations_project_id'), table_name='stock_locations')
    op.drop_table('stock_locations')
    # Drop the type too, or re-running the upgrade fails on CREATE TYPE
    sa.Enum(name='stock_location_kind').drop(op.get_bind(), checkfirst=True)
    # Postgres cannot drop a single enum value; the type is left as-is, which
    # is harmless because no row can reference 'transfer' once the tables above
    # are gone.
    # ### end Alembic commands ###
