"""m11_batch_tracking

Revision ID: 3f9e6acac5bf
Revises: a5829c36c8f8
Create Date: 2026-08-04 14:02:52.583786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3f9e6acac5bf'
down_revision: Union[str, None] = 'a5829c36c8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_batches',
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=60), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('supplier_ref', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stock_batches_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], name=op.f('fk_stock_batches_location_id_stock_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], name=op.f('fk_stock_batches_stock_item_id_stock_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_batches')),
    sa.UniqueConstraint('stock_item_id', 'location_id', 'batch_number', name=op.f('uq_stock_batches_stock_item_id_location_id_batch_number'))
    )
    op.create_index('ix_stock_batches_expiry', 'stock_batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_stock_batches_location_id'), 'stock_batches', ['location_id'], unique=False)
    op.create_index(op.f('ix_stock_batches_stock_item_id'), 'stock_batches', ['stock_item_id'], unique=False)
    tracking_mode = sa.Enum('none', 'batch', 'serial', name='tracking_mode')
    tracking_mode.create(op.get_bind(), checkfirst=True)
    # Existing items are untracked, which is exactly the old behaviour
    op.add_column(
        'stock_items',
        sa.Column('tracking_mode', tracking_mode, nullable=False, server_default='none'),
    )
    op.add_column('stock_items', sa.Column('expiry_warning_days', sa.Integer(), nullable=False, server_default='30'))
    op.add_column('stock_movements', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_stock_movements_batch_id'), 'stock_movements', ['batch_id'], unique=False)
    # NOTE: the two location foreign keys below were lost to an over-eager FK
    # strip when location_id was first added, so this migration is where those
    # columns finally get real referential integrity.
    op.create_foreign_key(op.f('fk_stock_movements_batch_id_stock_batches'), 'stock_movements', 'stock_batches', ['batch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_stock_movements_location_id_stock_locations'), 'stock_movements', 'stock_locations', ['location_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_stocktakes_location_id_stock_locations'), 'stocktakes', 'stock_locations', ['location_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_stocktakes_location_id_stock_locations'), 'stocktakes', type_='foreignkey')
    op.drop_constraint(op.f('fk_stock_movements_location_id_stock_locations'), 'stock_movements', type_='foreignkey')
    op.drop_constraint(op.f('fk_stock_movements_batch_id_stock_batches'), 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_batch_id'), table_name='stock_movements')
    op.drop_column('stock_movements', 'batch_id')
    op.drop_column('stock_items', 'expiry_warning_days')
    op.drop_column('stock_items', 'tracking_mode')
    op.drop_index(op.f('ix_stock_batches_stock_item_id'), table_name='stock_batches')
    op.drop_index(op.f('ix_stock_batches_location_id'), table_name='stock_batches')
    op.drop_index('ix_stock_batches_expiry', table_name='stock_batches')
    op.drop_table('stock_batches')
    sa.Enum(name='tracking_mode').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
