"""m10_stocktake_diary_labour

Revision ID: 44331b258a92
Revises: ff35e86c1a8f
Create Date: 2026-08-04 07:31:50.763537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '44331b258a92'
down_revision: Union[str, None] = 'ff35e86c1a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocktakes',
    sa.Column('doc_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('counting', 'approved', 'cancelled', name='stocktake_status'), nullable=False),
    sa.Column('count_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_stocktakes_approved_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stocktakes_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocktakes')),
    sa.UniqueConstraint('doc_number', name=op.f('uq_stocktakes_doc_number'))
    )
    op.create_table('stocktake_lines',
    sa.Column('stocktake_id', sa.UUID(), nullable=False),
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('expected_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('counted_quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], name=op.f('fk_stocktake_lines_stock_item_id_stock_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stocktake_id'], ['stocktakes.id'], name=op.f('fk_stocktake_lines_stocktake_id_stocktakes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocktake_lines')),
    sa.UniqueConstraint('stocktake_id', 'stock_item_id', name=op.f('uq_stocktake_lines_stocktake_id_stock_item_id'))
    )
    op.create_index(op.f('ix_stocktake_lines_stock_item_id'), 'stocktake_lines', ['stock_item_id'], unique=False)
    op.create_index(op.f('ix_stocktake_lines_stocktake_id'), 'stocktake_lines', ['stocktake_id'], unique=False)
    op.create_table('site_diary_labour',
    sa.Column('diary_entry_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overtime_quantity', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diary_entry_id'], ['site_diary_entries.id'], name=op.f('fk_site_diary_labour_diary_entry_id_site_diary_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_site_diary_labour_worker_id_workers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_diary_labour')),
    sa.UniqueConstraint('diary_entry_id', 'worker_id', name=op.f('uq_site_diary_labour_diary_entry_id_worker_id'))
    )
    op.create_index(op.f('ix_site_diary_labour_diary_entry_id'), 'site_diary_labour', ['diary_entry_id'], unique=False)
    op.create_index(op.f('ix_site_diary_labour_worker_id'), 'site_diary_labour', ['worker_id'], unique=False)
    op.alter_column('boq_items', 'variation_status',
               existing_type=postgresql.ENUM('proposed', 'approved', 'rejected', name='variation_status'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boq_items', 'variation_status',
               existing_type=postgresql.ENUM('proposed', 'approved', 'rejected', name='variation_status'),
               server_default=sa.text("'proposed'::variation_status"),
               existing_nullable=False)
    op.drop_index(op.f('ix_site_diary_labour_worker_id'), table_name='site_diary_labour')
    op.drop_index(op.f('ix_site_diary_labour_diary_entry_id'), table_name='site_diary_labour')
    op.drop_table('site_diary_labour')
    op.drop_index(op.f('ix_stocktake_lines_stocktake_id'), table_name='stocktake_lines')
    op.drop_index(op.f('ix_stocktake_lines_stock_item_id'), table_name='stocktake_lines')
    op.drop_table('stocktake_lines')
    op.drop_table('stocktakes')
    sa.Enum(name='stocktake_status').drop(op.get_bind(), checkfirst=True)
