"""accounting: chart of accounts, journals, general ledger

Revision ID: 473b688a832d
Revises: 1464a2d194c8
Create Date: 2026-08-05 08:38:56.376242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '473b688a832d'
down_revision: Union[str, None] = '1464a2d194c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.Enum('asset', 'liability', 'equity', 'revenue', 'expense', name='account_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=True)
    op.create_table('journals',
    sa.Column('doc_number', sa.String(length=30), nullable=False),
    sa.Column('journal_date', sa.Date(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'posted', 'reversed', name='journal_status'), nullable=False),
    sa.Column('source', sa.Enum('manual', 'cost_entry', 'valuation', 'goods_in', 'reversal', name='journal_source'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by', sa.UUID(), nullable=True),
    sa.Column('reversal_of', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_journals_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], name=op.f('fk_journals_posted_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_journals_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversal_of'], ['journals.id'], name=op.f('fk_journals_reversal_of_journals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journals'))
    )
    op.create_index('ix_journals_date', 'journals', ['journal_date'], unique=False)
    op.create_index(op.f('ix_journals_doc_number'), 'journals', ['doc_number'], unique=True)
    op.create_index(op.f('ix_journals_project_id'), 'journals', ['project_id'], unique=False)
    op.create_index('ix_journals_source', 'journals', ['source', 'source_id'], unique=False)
    op.create_table('journal_lines',
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(debit = 0 AND credit > 0) OR (debit > 0 AND credit = 0)', name=op.f('ck_journal_lines_ck_journal_lines_one_sided')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_journal_lines_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], name=op.f('fk_journal_lines_journal_id_journals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_lines'))
    )
    op.create_index(op.f('ix_journal_lines_account_id'), 'journal_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_journal_id'), 'journal_lines', ['journal_id'], unique=False)
    op.create_table('general_ledger',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('journal_line_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('doc_number', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('debit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_general_ledger_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], name=op.f('fk_general_ledger_journal_id_journals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_line_id'], ['journal_lines.id'], name=op.f('fk_general_ledger_journal_line_id_journal_lines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_general_ledger')),
    sa.UniqueConstraint('journal_line_id', name='uq_general_ledger_line')
    )
    op.create_index('ix_general_ledger_account_date', 'general_ledger', ['account_id', 'entry_date'], unique=False)
    op.create_index(op.f('ix_general_ledger_account_id'), 'general_ledger', ['account_id'], unique=False)
    op.create_index(op.f('ix_general_ledger_entry_date'), 'general_ledger', ['entry_date'], unique=False)
    op.create_index(op.f('ix_general_ledger_journal_id'), 'general_ledger', ['journal_id'], unique=False)
    op.create_index(op.f('ix_general_ledger_project_id'), 'general_ledger', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_general_ledger_project_id'), table_name='general_ledger')
    op.drop_index(op.f('ix_general_ledger_journal_id'), table_name='general_ledger')
    op.drop_index(op.f('ix_general_ledger_entry_date'), table_name='general_ledger')
    op.drop_index(op.f('ix_general_ledger_account_id'), table_name='general_ledger')
    op.drop_index('ix_general_ledger_account_date', table_name='general_ledger')
    op.drop_table('general_ledger')
    op.drop_index(op.f('ix_journal_lines_journal_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_account_id'), table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index('ix_journals_source', table_name='journals')
    op.drop_index(op.f('ix_journals_project_id'), table_name='journals')
    op.drop_index(op.f('ix_journals_doc_number'), table_name='journals')
    op.drop_index('ix_journals_date', table_name='journals')
    op.drop_table('journals')
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.drop_table('accounts')
    for name in ('journal_source', 'journal_status', 'account_type'):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
