"""supplier portal and invoices

Revision ID: 4c78528c8979
Revises: df58a69cba35
Create Date: 2026-09-01 08:12:32.330467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4c78528c8979'
down_revision: Union[str, None] = 'df58a69cba35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_access_tokens',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_supplier_access_tokens_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_access_tokens_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_access_tokens'))
    )
    op.create_index(op.f('ix_supplier_access_tokens_supplier_id'), 'supplier_access_tokens', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_access_tokens_token_hash'), 'supplier_access_tokens', ['token_hash'], unique=True)
    op.create_table('supplier_invoices',
    sa.Column('doc_number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('variance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_supplier_invoices_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_supplier_invoices_decided_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_supplier_invoices_purchase_order_id_purchase_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_invoices_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_invoices')),
    sa.UniqueConstraint('supplier_id', 'reference', name='uq_supplier_invoice_reference')
    )
    op.create_index(op.f('ix_supplier_invoices_doc_number'), 'supplier_invoices', ['doc_number'], unique=True)
    op.create_index(op.f('ix_supplier_invoices_purchase_order_id'), 'supplier_invoices', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_supplier_invoices_status'), 'supplier_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_invoices_supplier_id'), 'supplier_invoices', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_invoices_supplier_id'), table_name='supplier_invoices')
    op.drop_index(op.f('ix_supplier_invoices_status'), table_name='supplier_invoices')
    op.drop_index(op.f('ix_supplier_invoices_purchase_order_id'), table_name='supplier_invoices')
    op.drop_index(op.f('ix_supplier_invoices_doc_number'), table_name='supplier_invoices')
    op.drop_table('supplier_invoices')
    op.drop_index(op.f('ix_supplier_access_tokens_token_hash'), table_name='supplier_access_tokens')
    op.drop_index(op.f('ix_supplier_access_tokens_supplier_id'), table_name='supplier_access_tokens')
    op.drop_table('supplier_access_tokens')
    # ### end Alembic commands ###
