"""supplier payments and allocations

Revision ID: 633ef18dafae
Revises: bc9c9983c505
Create Date: 2026-08-05 12:31:55.203375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '633ef18dafae'
down_revision: Union[str, None] = 'bc9c9983c505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_payments',
    sa.Column('doc_number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('journal_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_supplier_payments_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], name=op.f('fk_supplier_payments_journal_id_journals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_payments_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_payments'))
    )
    op.create_index(op.f('ix_supplier_payments_doc_number'), 'supplier_payments', ['doc_number'], unique=True)
    op.create_index(op.f('ix_supplier_payments_payment_date'), 'supplier_payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_supplier_payments_supplier_id'), 'supplier_payments', ['supplier_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['supplier_payments.id'], name=op.f('fk_payment_allocations_payment_id_supplier_payments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_payment_allocations_purchase_order_id_purchase_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_allocations')),
    sa.UniqueConstraint('payment_id', 'purchase_order_id', name=op.f('uq_payment_allocations_payment_id_purchase_order_id'))
    )
    op.create_index(op.f('ix_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_purchase_order_id'), 'payment_allocations', ['purchase_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_allocations_purchase_order_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_payment_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_supplier_payments_supplier_id'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_payment_date'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_doc_number'), table_name='supplier_payments')
    op.drop_table('supplier_payments')
    # ### end Alembic commands ###
