"""subcontract variations, back-charges, withholding

Revision ID: 68fd7898d85b
Revises: b1ffed3e9552
Create Date: 2026-08-31 23:35:34.463504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68fd7898d85b'
down_revision: Union[str, None] = 'b1ffed3e9552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('back_charges',
    sa.Column('subcontract_id', sa.UUID(), nullable=False),
    sa.Column('doc_number', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('raised_on', sa.Date(), nullable=False),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('journal_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_back_charges_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], name=op.f('fk_back_charges_journal_id_journals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcontract_id'], ['subcontracts.id'], name=op.f('fk_back_charges_subcontract_id_subcontracts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_back_charges'))
    )
    op.create_index(op.f('ix_back_charges_doc_number'), 'back_charges', ['doc_number'], unique=True)
    op.create_index(op.f('ix_back_charges_subcontract_id'), 'back_charges', ['subcontract_id'], unique=False)
    op.create_table('subcontract_variations',
    sa.Column('subcontract_id', sa.UUID(), nullable=False),
    sa.Column('doc_number', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('instructed_on', sa.Date(), nullable=False),
    sa.Column('instructed_by', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_subcontract_variations_approved_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_subcontract_variations_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['subcontract_id'], ['subcontracts.id'], name=op.f('fk_subcontract_variations_subcontract_id_subcontracts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subcontract_variations'))
    )
    op.create_index(op.f('ix_subcontract_variations_doc_number'), 'subcontract_variations', ['doc_number'], unique=True)
    op.create_index(op.f('ix_subcontract_variations_subcontract_id'), 'subcontract_variations', ['subcontract_id'], unique=False)
    op.add_column('subcontracts', sa.Column('withholding_pct', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcontracts', 'withholding_pct')
    op.drop_index(op.f('ix_subcontract_variations_subcontract_id'), table_name='subcontract_variations')
    op.drop_index(op.f('ix_subcontract_variations_doc_number'), table_name='subcontract_variations')
    op.drop_table('subcontract_variations')
    op.drop_index(op.f('ix_back_charges_subcontract_id'), table_name='back_charges')
    op.drop_index(op.f('ix_back_charges_doc_number'), table_name='back_charges')
    op.drop_table('back_charges')
    # ### end Alembic commands ###
