"""trash: archive of deleted records

Revision ID: 7e5a0dc71fe2
Revises: 0de77b679595
Create Date: 2026-08-04 19:02:34.538171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7e5a0dc71fe2'
down_revision: Union[str, None] = '0de77b679595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_records',
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=60), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('deleted_by_name', sa.String(length=120), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restorable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('fk_deleted_records_deleted_by_id_users'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deleted_records'))
    )
    op.create_index(op.f('ix_deleted_records_deleted_at'), 'deleted_records', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_deleted_records_entity_id'), 'deleted_records', ['entity_id'], unique=False)
    op.create_index(op.f('ix_deleted_records_entity_type'), 'deleted_records', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deleted_records_entity_type'), table_name='deleted_records')
    op.drop_index(op.f('ix_deleted_records_entity_id'), table_name='deleted_records')
    op.drop_index(op.f('ix_deleted_records_deleted_at'), table_name='deleted_records')
    op.drop_table('deleted_records')
    # ### end Alembic commands ###
