"""supplier assessments

Revision ID: 8c727751ff6c
Revises: 4c78528c8979
Create Date: 2026-09-02 12:06:23.761947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8c727751ff6c'
down_revision: Union[str, None] = '4c78528c8979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_assessments',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('assessed_on', sa.Date(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('professionalism', sa.Integer(), nullable=True),
    sa.Column('would_use_again', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_supplier_assessments_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_supplier_assessments_purchase_order_id_purchase_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_assessments_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_assessments')),
    sa.UniqueConstraint('purchase_order_id', name='uq_assessment_per_order')
    )
    op.create_index(op.f('ix_supplier_assessments_supplier_id'), 'supplier_assessments', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_assessments_supplier_id'), table_name='supplier_assessments')
    op.drop_table('supplier_assessments')
    # ### end Alembic commands ###
