"""m5_payroll_portal_measurement_notifications

Revision ID: 90d84fa6a884
Revises: fff40dcfaf94
Create Date: 2026-08-03 04:21:58.835557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '90d84fa6a884'
down_revision: Union[str, None] = 'fff40dcfaf94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_runs',
    sa.Column('doc_number', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', name='pay_run_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('overtime_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('allowance_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deduction_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_pay_runs_approved_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_pay_runs_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pay_runs')),
    sa.UniqueConstraint('doc_number', name=op.f('uq_pay_runs_doc_number'))
    )
    op.create_index('uq_pay_runs_single_draft', 'pay_runs', ['status'], unique=True, postgresql_where=sa.text("status = 'draft'"))
    op.create_table('workers',
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('trade', sa.String(length=60), nullable=False),
    sa.Column('national_id', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('pay_basis', sa.Enum('hourly', 'daily', name='pay_basis'), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workers_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workers'))
    )
    op.create_table('client_access_tokens',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_access_tokens_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_client_access_tokens_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_access_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_client_access_tokens_token_hash'))
    )
    op.create_index(op.f('ix_client_access_tokens_client_id'), 'client_access_tokens', ['client_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link_path', sa.String(length=200), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('pay_run_lines',
    sa.Column('pay_run_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('worker_name', sa.String(length=120), nullable=False),
    sa.Column('trade', sa.String(length=60), nullable=False),
    sa.Column('pay_basis', sa.Enum('hourly', 'daily', name='pay_basis'), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('overtime_quantity', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('base_pay', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('overtime_pay', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('allowance_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deduction_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_pay', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pay_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('project_allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pay_run_id'], ['pay_runs.id'], name=op.f('fk_pay_run_lines_pay_run_id_pay_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_pay_run_lines_worker_id_workers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pay_run_lines')),
    sa.UniqueConstraint('pay_run_id', 'worker_id', name=op.f('uq_pay_run_lines_pay_run_id_worker_id'))
    )
    op.create_index(op.f('ix_pay_run_lines_pay_run_id'), 'pay_run_lines', ['pay_run_id'], unique=False)
    op.create_index(op.f('ix_pay_run_lines_worker_id'), 'pay_run_lines', ['worker_id'], unique=False)
    op.create_table('worker_pay_items',
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('allowance', 'deduction', name='pay_item_kind'), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_worker_pay_items_worker_id_workers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_pay_items'))
    )
    op.create_index(op.f('ix_worker_pay_items_worker_id'), 'worker_pay_items', ['worker_id'], unique=False)
    op.create_table('timesheets',
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overtime_quantity', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pay_run_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_timesheets_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['pay_run_id'], ['pay_runs.id'], name=op.f('fk_timesheets_pay_run_id_pay_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_timesheets_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_timesheets_worker_id_workers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timesheets')),
    sa.UniqueConstraint('worker_id', 'project_id', 'work_date', name=op.f('uq_timesheets_worker_id_project_id_work_date'))
    )
    op.create_index(op.f('ix_timesheets_pay_run_id'), 'timesheets', ['pay_run_id'], unique=False)
    op.create_index(op.f('ix_timesheets_project_id'), 'timesheets', ['project_id'], unique=False)
    op.create_index(op.f('ix_timesheets_work_date'), 'timesheets', ['work_date'], unique=False)
    op.create_index(op.f('ix_timesheets_worker_id'), 'timesheets', ['worker_id'], unique=False)
    op.create_table('valuation_lines',
    sa.Column('valuation_id', sa.UUID(), nullable=False),
    sa.Column('boq_item_id', sa.UUID(), nullable=True),
    sa.Column('item_code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('boq_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('qty_to_date', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], name=op.f('fk_valuation_lines_boq_item_id_boq_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['valuation_id'], ['valuations.id'], name=op.f('fk_valuation_lines_valuation_id_valuations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_valuation_lines')),
    sa.UniqueConstraint('valuation_id', 'boq_item_id', name=op.f('uq_valuation_lines_valuation_id_boq_item_id'))
    )
    op.create_index(op.f('ix_valuation_lines_boq_item_id'), 'valuation_lines', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_valuation_lines_valuation_id'), 'valuation_lines', ['valuation_id'], unique=False)
    # (spurious use_alter created_by FK re-detections stripped — recurring autogenerate quirk)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valuation_lines_valuation_id'), table_name='valuation_lines')
    op.drop_index(op.f('ix_valuation_lines_boq_item_id'), table_name='valuation_lines')
    op.drop_table('valuation_lines')
    op.drop_index(op.f('ix_timesheets_worker_id'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_work_date'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_project_id'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_pay_run_id'), table_name='timesheets')
    op.drop_table('timesheets')
    op.drop_index(op.f('ix_worker_pay_items_worker_id'), table_name='worker_pay_items')
    op.drop_table('worker_pay_items')
    op.drop_index(op.f('ix_pay_run_lines_worker_id'), table_name='pay_run_lines')
    op.drop_index(op.f('ix_pay_run_lines_pay_run_id'), table_name='pay_run_lines')
    op.drop_table('pay_run_lines')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_client_access_tokens_client_id'), table_name='client_access_tokens')
    op.drop_table('client_access_tokens')
    op.drop_table('workers')
    op.drop_index('uq_pay_runs_single_draft', table_name='pay_runs', postgresql_where=sa.text("status = 'draft'"))
    op.drop_table('pay_runs')
    sa.Enum(name='pay_run_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='pay_item_kind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='pay_basis').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
