"""editable permission matrix

Revision ID: 9b45e3e13ac9
Revises: e6cd865b578b
Create Date: 2026-08-06 07:40:15.014145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '9b45e3e13ac9'
down_revision: Union[str, None] = 'e6cd865b578b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('role', postgresql.ENUM(name='user_role', create_type=False), nullable=False),
    sa.Column('permission', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role', 'permission', name=op.f('uq_role_permissions_role_permission'))
    )
    op.create_index(op.f('ix_role_permissions_permission'), 'role_permissions', ['permission'], unique=False)
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=False)
    op.create_table('user_permission_overrides',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=40), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_permission_overrides_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_permission_overrides')),
    sa.UniqueConstraint('user_id', 'permission', name=op.f('uq_user_permission_overrides_user_id_permission'))
    )
    op.create_index(op.f('ix_user_permission_overrides_permission'), 'user_permission_overrides', ['permission'], unique=False)
    op.create_index(op.f('ix_user_permission_overrides_user_id'), 'user_permission_overrides', ['user_id'], unique=False)
    op.alter_column('accounts', 'report_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('accounts', 'account_class',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('accounts', 'account_subclass',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('accounts', 'is_postable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('accounts', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bank_accounts', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_accounts', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'USD'::character varying"),
               existing_nullable=False)
    op.alter_column('accounts', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'USD'::character varying"),
               existing_nullable=False)
    op.alter_column('accounts', 'is_postable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('accounts', 'account_subclass',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'current_assets'::character varying"),
               existing_nullable=False)
    op.alter_column('accounts', 'account_class',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'asset'::character varying"),
               existing_nullable=False)
    op.alter_column('accounts', 'report_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'balance_sheet'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_permission_overrides_user_id'), table_name='user_permission_overrides')
    op.drop_index(op.f('ix_user_permission_overrides_permission'), table_name='user_permission_overrides')
    op.drop_table('user_permission_overrides')
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission'), table_name='role_permissions')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
