"""media client op id

Revision ID: 9e875560ff6b
Revises: 68fd7898d85b
Create Date: 2026-09-01 07:15:39.865065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9e875560ff6b'
down_revision: Union[str, None] = '68fd7898d85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('client_op_id', sa.UUID(), nullable=True))
    op.create_index('ux_media_files_client_op', 'media_files', ['client_op_id'], unique=True, postgresql_where=sa.text('client_op_id IS NOT NULL'))
    op.alter_column('subcontracts', 'withholding_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subcontracts', 'withholding_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.drop_index('ux_media_files_client_op', table_name='media_files', postgresql_where=sa.text('client_op_id IS NOT NULL'))
    op.drop_column('media_files', 'client_op_id')
    # ### end Alembic commands ###
