"""m11_stocktake_location

Revision ID: a5829c36c8f8
Revises: 3866c4b89855
Create Date: 2026-08-04 12:26:45.751621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a5829c36c8f8'
down_revision: Union[str, None] = '3866c4b89855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocktakes', sa.Column('location_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_stocktakes_location_id'), 'stocktakes', ['location_id'], unique=False)
    # Counts taken before locations existed were counts of the only store
    op.execute(
        """
        UPDATE stocktakes
        SET location_id = (SELECT id FROM stock_locations WHERE is_default)
        WHERE location_id IS NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocktakes_location_id'), table_name='stocktakes')
    op.drop_column('stocktakes', 'location_id')
    # ### end Alembic commands ###
