"""retention releases

Revision ID: af5aa8301bbf
Revises: 8d78eeb23a5c
Create Date: 2026-08-31 09:28:34.713831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'af5aa8301bbf'
down_revision: Union[str, None] = '8d78eeb23a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retention_releases',
    sa.Column('subcontract_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('released_on', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('journal_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_retention_releases_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], name=op.f('fk_retention_releases_journal_id_journals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcontract_id'], ['subcontracts.id'], name=op.f('fk_retention_releases_subcontract_id_subcontracts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_releases'))
    )
    op.create_index(op.f('ix_retention_releases_subcontract_id'), 'retention_releases', ['subcontract_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retention_releases_subcontract_id'), table_name='retention_releases')
    op.drop_table('retention_releases')
    # ### end Alembic commands ###
