"""plant recharge, certificates, depreciation

Revision ID: b1ffed3e9552
Revises: af5aa8301bbf
Create Date: 2026-08-31 16:59:22.523041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'b1ffed3e9552'
down_revision: Union[str, None] = 'af5aa8301bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depreciation_charges',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('journal_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_depreciation_charges_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_depreciation_charges_equipment_id_equipment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], name=op.f('fk_depreciation_charges_journal_id_journals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_depreciation_charges')),
    sa.UniqueConstraint('equipment_id', 'period_start', name='uq_depreciation_period')
    )
    op.create_index(op.f('ix_depreciation_charges_equipment_id'), 'depreciation_charges', ['equipment_id'], unique=False)
    op.create_table('equipment_certificates',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('cert_type', sa.Enum('insurance', 'roadworthiness', 'thorough_examination', 'fitness', 'calibration', 'operator_licence', 'other', name='equipment_cert_type'), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_equipment_certificates_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_equipment_certificates_equipment_id_equipment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], name=op.f('fk_equipment_certificates_media_id_media_files'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_certificates'))
    )
    op.create_index(op.f('ix_equipment_certificates_equipment_id'), 'equipment_certificates', ['equipment_id'], unique=False)
    op.create_index('ix_equipment_certificates_equipment_type', 'equipment_certificates', ['equipment_id', 'cert_type'], unique=False)
    op.create_table('plant_recharges',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('units', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cost_entry_id', sa.UUID(), nullable=True),
    sa.Column('journal_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cost_entry_id'], ['cost_entries.id'], name=op.f('fk_plant_recharges_cost_entry_id_cost_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_plant_recharges_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_plant_recharges_equipment_id_equipment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], name=op.f('fk_plant_recharges_journal_id_journals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_plant_recharges_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plant_recharges')),
    sa.UniqueConstraint('equipment_id', 'project_id', 'period_start', name='uq_plant_recharge_period')
    )
    op.create_index(op.f('ix_plant_recharges_equipment_id'), 'plant_recharges', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_plant_recharges_project_id'), 'plant_recharges', ['project_id'], unique=False)
    # add_column does not emit CREATE TYPE, so the type is made first. The
    # server default lets the existing settings row take a value; it is then
    # dropped so the application, not the database, owns the default.
    costing = postgresql.ENUM('direct', 'internal_hire', name='plant_costing_mode', create_type=False)
    costing.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'company_settings',
        sa.Column('plant_costing_mode', costing, nullable=False, server_default='direct'),
    )
    op.alter_column('company_settings', 'plant_costing_mode', server_default=None)
    # Backfilled from the meter each machine is on today. For an existing
    # fleet that is the closest true statement available: any earlier
    # opening was never recorded.
    op.add_column(
        'equipment',
        sa.Column('opening_meter', sa.Numeric(precision=14, scale=2), nullable=False,
                  server_default='0'),
    )
    op.execute('UPDATE equipment SET opening_meter = current_meter')
    op.alter_column('equipment', 'opening_meter', server_default=None)
    op.add_column('equipment', sa.Column('residual_value', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('equipment', sa.Column('useful_life_months', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'useful_life_months')
    op.drop_column('equipment', 'residual_value')
    op.drop_column('equipment', 'opening_meter')
    op.drop_column('company_settings', 'plant_costing_mode')
    sa.Enum(name='plant_costing_mode').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_plant_recharges_project_id'), table_name='plant_recharges')
    op.drop_index(op.f('ix_plant_recharges_equipment_id'), table_name='plant_recharges')
    op.drop_table('plant_recharges')
    op.drop_index('ix_equipment_certificates_equipment_type', table_name='equipment_certificates')
    op.drop_index(op.f('ix_equipment_certificates_equipment_id'), table_name='equipment_certificates')
    op.drop_table('equipment_certificates')
    sa.Enum(name='equipment_cert_type').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_depreciation_charges_equipment_id'), table_name='depreciation_charges')
    op.drop_table('depreciation_charges')
    # ### end Alembic commands ###
