"""subsidiary ledgers

Revision ID: b5ede1f20e57
Revises: 9b45e3e13ac9
Create Date: 2026-08-06 10:31:52.289933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b5ede1f20e57'
down_revision: Union[str, None] = '9b45e3e13ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subsidiary_accounts',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('control_account_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['control_account_id'], ['accounts.id'], name=op.f('fk_subsidiary_accounts_control_account_id_accounts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subsidiary_accounts')),
    sa.UniqueConstraint('entity_type', 'entity_id', 'currency', name='uq_subsidiary_party')
    )
    op.create_index(op.f('ix_subsidiary_accounts_code'), 'subsidiary_accounts', ['code'], unique=True)
    op.create_index(op.f('ix_subsidiary_accounts_control_account_id'), 'subsidiary_accounts', ['control_account_id'], unique=False)
    op.create_index(op.f('ix_subsidiary_accounts_entity_id'), 'subsidiary_accounts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_subsidiary_accounts_entity_type'), 'subsidiary_accounts', ['entity_type'], unique=False)
    op.create_table('subsidiary_entries',
    sa.Column('subsidiary_id', sa.UUID(), nullable=False),
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('journal_line_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('doc_number', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('debit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], name=op.f('fk_subsidiary_entries_journal_id_journals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_line_id'], ['journal_lines.id'], name=op.f('fk_subsidiary_entries_journal_line_id_journal_lines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subsidiary_id'], ['subsidiary_accounts.id'], name=op.f('fk_subsidiary_entries_subsidiary_id_subsidiary_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subsidiary_entries')),
    sa.UniqueConstraint('journal_line_id', name='uq_subsidiary_entry_line')
    )
    op.create_index('ix_subsidiary_entries_account_date', 'subsidiary_entries', ['subsidiary_id', 'entry_date'], unique=False)
    op.create_index(op.f('ix_subsidiary_entries_entry_date'), 'subsidiary_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_subsidiary_entries_journal_id'), 'subsidiary_entries', ['journal_id'], unique=False)
    op.create_index(op.f('ix_subsidiary_entries_project_id'), 'subsidiary_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_subsidiary_entries_subsidiary_id'), 'subsidiary_entries', ['subsidiary_id'], unique=False)
    op.add_column('journal_lines', sa.Column('subsidiary_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_journal_lines_subsidiary_id'), 'journal_lines', ['subsidiary_id'], unique=False)
    op.create_foreign_key(op.f('fk_journal_lines_subsidiary_id_subsidiary_accounts'), 'journal_lines', 'subsidiary_accounts', ['subsidiary_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_journal_lines_subsidiary_id_subsidiary_accounts'), 'journal_lines', type_='foreignkey')
    op.drop_index(op.f('ix_journal_lines_subsidiary_id'), table_name='journal_lines')
    op.drop_column('journal_lines', 'subsidiary_id')
    op.drop_index(op.f('ix_subsidiary_entries_subsidiary_id'), table_name='subsidiary_entries')
    op.drop_index(op.f('ix_subsidiary_entries_project_id'), table_name='subsidiary_entries')
    op.drop_index(op.f('ix_subsidiary_entries_journal_id'), table_name='subsidiary_entries')
    op.drop_index(op.f('ix_subsidiary_entries_entry_date'), table_name='subsidiary_entries')
    op.drop_index('ix_subsidiary_entries_account_date', table_name='subsidiary_entries')
    op.drop_table('subsidiary_entries')
    op.drop_index(op.f('ix_subsidiary_accounts_entity_type'), table_name='subsidiary_accounts')
    op.drop_index(op.f('ix_subsidiary_accounts_entity_id'), table_name='subsidiary_accounts')
    op.drop_index(op.f('ix_subsidiary_accounts_control_account_id'), table_name='subsidiary_accounts')
    op.drop_index(op.f('ix_subsidiary_accounts_code'), table_name='subsidiary_accounts')
    op.drop_table('subsidiary_accounts')
    # ### end Alembic commands ###
