"""rfq supplier invites

Revision ID: bc9c9983c505
Revises: 473b688a832d
Create Date: 2026-08-05 09:45:30.083066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bc9c9983c505'
down_revision: Union[str, None] = '473b688a832d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfq_invites',
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_rfq_invites_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], name=op.f('fk_rfq_invites_rfq_id_rfqs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_rfq_invites_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rfq_invites')),
    sa.UniqueConstraint('rfq_id', 'supplier_id', name=op.f('uq_rfq_invites_rfq_id_supplier_id'))
    )
    op.create_index(op.f('ix_rfq_invites_rfq_id'), 'rfq_invites', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_rfq_invites_supplier_id'), 'rfq_invites', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_rfq_invites_token_hash'), 'rfq_invites', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rfq_invites_token_hash'), table_name='rfq_invites')
    op.drop_index(op.f('ix_rfq_invites_supplier_id'), table_name='rfq_invites')
    op.drop_index(op.f('ix_rfq_invites_rfq_id'), table_name='rfq_invites')
    op.drop_table('rfq_invites')
    # ### end Alembic commands ###
