"""stock loss reasons

Revision ID: df58a69cba35
Revises: 9e875560ff6b
Create Date: 2026-09-01 07:40:00.643472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'df58a69cba35'
down_revision: Union[str, None] = '9e875560ff6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    reason = postgresql.ENUM(
        'correction', 'wastage', 'breakage', 'theft', 'expiry', 'site_loss',
        name='stock_loss_reason', create_type=False,
    )
    reason.create(op.get_bind(), checkfirst=True)
    op.add_column('stock_movements', sa.Column('loss_reason', reason, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_movements', 'loss_reason')
    sa.Enum(name='stock_loss_reason').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
