"""accounting depth: taxonomy, currency, periods, banks

Revision ID: e6cd865b578b
Revises: 633ef18dafae
Create Date: 2026-08-06 07:13:42.299988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e6cd865b578b'
down_revision: Union[str, None] = '633ef18dafae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchange_rates')),
    sa.UniqueConstraint('from_currency', 'to_currency', 'effective_date', name=op.f('uq_exchange_rates_from_currency_to_currency_effective_date'))
    )
    op.create_index(op.f('ix_exchange_rates_effective_date'), 'exchange_rates', ['effective_date'], unique=False)
    op.create_index(op.f('ix_exchange_rates_from_currency'), 'exchange_rates', ['from_currency'], unique=False)
    op.create_index(op.f('ix_exchange_rates_to_currency'), 'exchange_rates', ['to_currency'], unique=False)
    op.create_table('fiscal_periods',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_fiscal_periods_closed_by_users'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fiscal_periods')),
    sa.UniqueConstraint('year', 'month', name=op.f('uq_fiscal_periods_year_month'))
    )
    op.create_index(op.f('ix_fiscal_periods_year'), 'fiscal_periods', ['year'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('branch', sa.String(length=120), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False, server_default='USD'),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('gl_account_id', sa.UUID(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_bank_accounts_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['gl_account_id'], ['accounts.id'], name=op.f('fk_bank_accounts_gl_account_id_accounts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_accounts')),
    sa.UniqueConstraint('gl_account_id', name=op.f('uq_bank_accounts_gl_account_id'))
    )
    op.create_table('bank_transactions',
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('matched_journal_id', sa.UUID(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('fk_bank_transactions_bank_account_id_bank_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_journal_id'], ['journals.id'], name=op.f('fk_bank_transactions_matched_journal_id_journals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_transactions'))
    )
    op.create_index(op.f('ix_bank_transactions_bank_account_id'), 'bank_transactions', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_matched_journal_id'), 'bank_transactions', ['matched_journal_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_date'), 'bank_transactions', ['transaction_date'], unique=False)
    op.add_column('accounts', sa.Column('report_type', sa.String(length=20), nullable=False, server_default='balance_sheet'))
    op.add_column('accounts', sa.Column('account_class', sa.String(length=20), nullable=False, server_default='asset'))
    op.add_column('accounts', sa.Column('account_subclass', sa.String(length=30), nullable=False, server_default='current_assets'))
    op.add_column('accounts', sa.Column('account_type_label', sa.String(length=60), nullable=True))
    op.add_column('accounts', sa.Column('account_subtype', sa.String(length=60), nullable=True))
    op.add_column('accounts', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('accounts', sa.Column('is_postable', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('accounts', sa.Column('currency', sa.String(length=3), nullable=False, server_default='USD'))
    op.create_index(op.f('ix_accounts_account_subclass'), 'accounts', ['account_subclass'], unique=False)
    op.create_index(op.f('ix_accounts_currency'), 'accounts', ['currency'], unique=False)
    op.create_index(op.f('ix_accounts_parent_id'), 'accounts', ['parent_id'], unique=False)
    op.create_foreign_key(op.f('fk_accounts_parent_id_accounts'), 'accounts', 'accounts', ['parent_id'], ['id'], ondelete='RESTRICT')

    # The blanket server_default above is only there to let the column land on
    # existing rows. Every account's real subclass is decided by the range its
    # code falls in, so put each one where the chart says it belongs.
    op.execute("""
        UPDATE accounts SET
            account_subclass = CASE
                WHEN code::int BETWEEN 1    AND 999  THEN 'noncurrent_assets'
                WHEN code::int BETWEEN 1000 AND 1999 THEN 'current_assets'
                WHEN code::int BETWEEN 2000 AND 2999 THEN 'current_liabilities'
                WHEN code::int BETWEEN 3000 AND 3999 THEN 'equity'
                WHEN code::int BETWEEN 4000 AND 4999 THEN 'revenue'
                WHEN code::int BETWEEN 5000 AND 5999 THEN 'cost_of_works'
                WHEN code::int BETWEEN 6000 AND 6999 THEN 'overheads'
                WHEN code::int BETWEEN 7000 AND 7999 THEN 'other_income_expense'
                WHEN code::int BETWEEN 8000 AND 8999 THEN 'taxation'
                ELSE 'suspense'
            END,
            account_class = CASE account_type
                WHEN 'asset' THEN 'asset'
                WHEN 'liability' THEN 'liability'
                WHEN 'equity' THEN 'equity'
                WHEN 'revenue' THEN 'income'
                ELSE 'expense'
            END,
            report_type = CASE
                WHEN account_type IN ('revenue', 'expense') THEN 'profit_loss'
                ELSE 'balance_sheet'
            END
        WHERE code ~ '^[0-9]+$'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_accounts_parent_id_accounts'), 'accounts', type_='foreignkey')
    op.drop_index(op.f('ix_accounts_parent_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_currency'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_subclass'), table_name='accounts')
    op.drop_column('accounts', 'currency')
    op.drop_column('accounts', 'is_postable')
    op.drop_column('accounts', 'parent_id')
    op.drop_column('accounts', 'account_subtype')
    op.drop_column('accounts', 'account_type_label')
    op.drop_column('accounts', 'account_subclass')
    op.drop_column('accounts', 'account_class')
    op.drop_column('accounts', 'report_type')
    op.drop_index(op.f('ix_bank_transactions_transaction_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_matched_journal_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_account_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_fiscal_periods_year'), table_name='fiscal_periods')
    op.drop_table('fiscal_periods')
    op.drop_index(op.f('ix_exchange_rates_to_currency'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_from_currency'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_effective_date'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
