"""vendor compliance and subcontracts

Revision ID: eb480524ac36
Revises: 01653f2984a2
Create Date: 2026-08-30 23:49:08.823381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'eb480524ac36'
down_revision: Union[str, None] = '01653f2984a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_requirements',
    sa.Column('doc_type', sa.Enum('tax_clearance', 'vat_registration', 'company_registration', 'public_liability', 'workmans_compensation', 'safety_certificate', 'bank_confirmation', 'trade_licence', 'other', name='compliance_doc_type'), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('warn_days', sa.Integer(), nullable=False),
    sa.Column('applies_to', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_requirements')),
    sa.UniqueConstraint('doc_type', name='uq_compliance_requirement_type')
    )
    op.create_table('compliance_documents',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', postgresql.ENUM(name='compliance_doc_type', create_type=False), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_compliance_documents_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], name=op.f('fk_compliance_documents_media_id_media_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_compliance_documents_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_documents'))
    )
    op.create_index(op.f('ix_compliance_documents_supplier_id'), 'compliance_documents', ['supplier_id'], unique=False)
    op.create_index('ix_compliance_expiry', 'compliance_documents', ['expires_on'], unique=False)
    op.create_index('ix_compliance_supplier_type', 'compliance_documents', ['supplier_id', 'doc_type'], unique=False)
    op.create_table('subcontracts',
    sa.Column('doc_number', sa.String(length=30), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('retention_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'awarded', 'completed', 'terminated', name='subcontract_status'), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('awarded_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['awarded_by'], ['users.id'], name=op.f('fk_subcontracts_awarded_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_subcontracts_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_subcontracts_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_subcontracts_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subcontracts'))
    )
    op.create_index(op.f('ix_subcontracts_doc_number'), 'subcontracts', ['doc_number'], unique=True)
    op.create_index(op.f('ix_subcontracts_project_id'), 'subcontracts', ['project_id'], unique=False)
    op.create_index(op.f('ix_subcontracts_status'), 'subcontracts', ['status'], unique=False)
    op.create_index(op.f('ix_subcontracts_supplier_id'), 'subcontracts', ['supplier_id'], unique=False)
    op.create_table('subcontract_milestones',
    sa.Column('subcontract_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'submitted', 'certified', 'rejected', name='milestone_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('certified_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('retention_held', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('certified_on', sa.Date(), nullable=True),
    sa.Column('certified_by', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('cost_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['certified_by'], ['users.id'], name=op.f('fk_subcontract_milestones_certified_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['cost_entry_id'], ['cost_entries.id'], name=op.f('fk_subcontract_milestones_cost_entry_id_cost_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_subcontract_milestones_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['subcontract_id'], ['subcontracts.id'], name=op.f('fk_subcontract_milestones_subcontract_id_subcontracts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subcontract_milestones'))
    )
    op.create_index(op.f('ix_subcontract_milestones_status'), 'subcontract_milestones', ['status'], unique=False)
    op.create_index(op.f('ix_subcontract_milestones_subcontract_id'), 'subcontract_milestones', ['subcontract_id'], unique=False)
    # add_column does not emit CREATE TYPE, so the type has to exist first.
    vendor_status = postgresql.ENUM(
        'pending', 'approved', 'suspended', 'blacklisted',
        name='vendor_status', create_type=False,
    )
    vendor_status.create(op.get_bind(), checkfirst=True)
    op.add_column('suppliers', sa.Column('vendor_status', vendor_status, server_default='pending', nullable=False))
    op.add_column('suppliers', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('suppliers', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_suppliers_vendor_status'), 'suppliers', ['vendor_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_vendor_status'), table_name='suppliers')
    op.drop_column('suppliers', 'approved_by')
    op.drop_column('suppliers', 'approved_at')
    op.drop_column('suppliers', 'vendor_status')
    op.drop_index(op.f('ix_subcontract_milestones_subcontract_id'), table_name='subcontract_milestones')
    op.drop_index(op.f('ix_subcontract_milestones_status'), table_name='subcontract_milestones')
    op.drop_table('subcontract_milestones')
    op.drop_index(op.f('ix_subcontracts_supplier_id'), table_name='subcontracts')
    op.drop_index(op.f('ix_subcontracts_status'), table_name='subcontracts')
    op.drop_index(op.f('ix_subcontracts_project_id'), table_name='subcontracts')
    op.drop_index(op.f('ix_subcontracts_doc_number'), table_name='subcontracts')
    op.drop_table('subcontracts')
    op.drop_index('ix_compliance_supplier_type', table_name='compliance_documents')
    op.drop_index('ix_compliance_expiry', table_name='compliance_documents')
    op.drop_index(op.f('ix_compliance_documents_supplier_id'), table_name='compliance_documents')
    op.drop_table('compliance_documents')
    op.drop_table('compliance_requirements')
    for name in ('milestone_status', 'subcontract_status', 'compliance_doc_type', 'vendor_status'):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
