"""m9_task_baseline

Revision ID: fce3d69adadb
Revises: 0394c599d4f6
Create Date: 2026-08-04 06:55:48.028314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fce3d69adadb'
down_revision: Union[str, None] = '0394c599d4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('baseline_start', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('baseline_end', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'baseline_end')
    op.drop_column('tasks', 'baseline_start')
    # ### end Alembic commands ###
