"""m4 valuations store receipt ingestion

Revision ID: fff40dcfaf94
Revises: 2142af130047
Create Date: 2026-08-02 18:58:27.474837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fff40dcfaf94'
down_revision: Union[str, None] = '2142af130047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_items',
    sa.Column('status', sa.Enum('received', 'failed', 'needs_info', 'drafted', 'posted', 'rejected', name='ingestion_status'), nullable=False),
    sa.Column('channel', sa.Enum('upload', name='ingestion_channel'), nullable=False),
    sa.Column('doc_type', sa.Enum('supplier_invoice', 'expense_receipt', 'delivery_note', 'supplier_quote', name='ingestion_doc_type'), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proposed_action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ingestion_items_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ingestion_items_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_ingestion_items_reviewed_by_users'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_items'))
    )
    op.create_index(op.f('ix_ingestion_items_doc_type'), 'ingestion_items', ['doc_type'], unique=False)
    op.create_index(op.f('ix_ingestion_items_project_id'), 'ingestion_items', ['project_id'], unique=False)
    op.create_index('ix_ingestion_items_sha256', 'ingestion_items', ['file_sha256'], unique=False)
    op.create_index('ix_ingestion_items_status_created', 'ingestion_items', ['status', 'created_at'], unique=False)
    op.create_table('valuations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('doc_number', sa.String(length=20), nullable=False),
    sa.Column('valuation_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'paid', 'cancelled', name='valuation_status'), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_valuation', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('retention_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('previous_certified', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_certified', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_valuations_created_by_users'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_valuations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_valuations')),
    sa.UniqueConstraint('doc_number', name=op.f('uq_valuations_doc_number')),
    sa.UniqueConstraint('project_id', 'valuation_number', name=op.f('uq_valuations_project_id_valuation_number'))
    )
    op.create_index(op.f('ix_valuations_project_id'), 'valuations', ['project_id'], unique=False)
    op.create_index('uq_valuations_project_draft', 'valuations', ['project_id'], unique=True, postgresql_where=sa.text("status = 'draft'"))
    # add_column does not auto-create enum types (unlike create_table)
    sa.Enum('project', 'store', name='po_destination').create(op.get_bind(), checkfirst=True)
    op.add_column('purchase_orders', sa.Column('received_to', sa.Enum('project', 'store', name='po_destination', create_type=False), nullable=True))
    # Pre-M4 receipts were all direct-to-project
    op.execute("UPDATE purchase_orders SET received_to = 'project' WHERE status = 'received'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'received_to')
    sa.Enum(name='po_destination').drop(op.get_bind(), checkfirst=True)
    op.drop_index('uq_valuations_project_draft', table_name='valuations', postgresql_where=sa.text("status = 'draft'"))
    op.drop_index(op.f('ix_valuations_project_id'), table_name='valuations')
    op.drop_table('valuations')
    op.drop_index('ix_ingestion_items_status_created', table_name='ingestion_items')
    op.drop_index('ix_ingestion_items_sha256', table_name='ingestion_items')
    op.drop_index(op.f('ix_ingestion_items_project_id'), table_name='ingestion_items')
    op.drop_index(op.f('ix_ingestion_items_doc_type'), table_name='ingestion_items')
    op.drop_table('ingestion_items')
    # ### end Alembic commands ###
