"""Shared PDF document builder (fpdf2).

One visual language for every generated document — payment certificates,
purchase orders, payslips: letterhead band in the brand blue used by the XLSX
exports, key-value meta grid, zebra line tables, bold totals band, footer with
page numbers. All money is rendered pre-formatted by callers via `money()`.
"""

from dataclasses import dataclass
from decimal import Decimal

from fpdf import FPDF

BRAND = (42, 75, 141)  # 2A4B8D — matches report XLSX header fill
INK = (33, 37, 41)
MUTED = (108, 117, 125)
RULE = (222, 226, 230)
ZEBRA = (246, 248, 250)

MARGIN = 16


def money(value: Decimal | float | str | None) -> str:
    if value is None:
        return "-"
    return f"{Decimal(str(value)):,.2f}"


_LATIN_FALLBACKS = str.maketrans(
    {"—": "-", "–": "-", "’": "'", "‘": "'", "“": '"', "”": '"', "…": "...", "→": ">", "·": "-"}
)


def _latin(text: str) -> str:
    """Core PDF fonts are latin-1 only; degrade gracefully instead of 500ing
    on an em dash in a project name."""
    return str(text).translate(_LATIN_FALLBACKS).encode("latin-1", "replace").decode("latin-1")


@dataclass
class Col:
    label: str
    width: float  # fraction of usable width
    align: str = "L"  # L | R | C


class DocumentPdf(FPDF):
    def __init__(self, company_name: str, doc_title: str, doc_number: str):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.company_name = company_name
        self.doc_title = doc_title
        self.doc_number = doc_number
        self.set_margins(MARGIN, MARGIN, MARGIN)
        self.set_auto_page_break(auto=True, margin=22)
        self.add_page()

    @property
    def usable(self) -> float:
        return self.w - 2 * MARGIN

    def cell(self, *args, **kwargs):  # type: ignore[override]
        if len(args) >= 3 and isinstance(args[2], str):
            args = (*args[:2], _latin(args[2]), *args[3:])
        if isinstance(kwargs.get("text"), str):
            kwargs["text"] = _latin(kwargs["text"])
        return super().cell(*args, **kwargs)

    def multi_cell(self, *args, **kwargs):  # type: ignore[override]
        if len(args) >= 3 and isinstance(args[2], str):
            args = (*args[:2], _latin(args[2]), *args[3:])
        if isinstance(kwargs.get("text"), str):
            kwargs["text"] = _latin(kwargs["text"])
        return super().multi_cell(*args, **kwargs)

    # --- chrome -------------------------------------------------------------

    def header(self) -> None:  # fpdf hook, runs on every page
        self.set_fill_color(*BRAND)
        self.rect(0, 0, self.w, 3, style="F")
        self.set_y(9)
        self.set_font("helvetica", "B", 15)
        self.set_text_color(*BRAND)
        self.cell(self.usable / 2, 8, self.company_name, align="L")
        self.set_font("helvetica", "B", 13)
        self.set_text_color(*INK)
        self.cell(
            self.usable / 2, 8, self.doc_title.upper(), align="R", new_x="LMARGIN", new_y="NEXT"
        )
        self.set_font("helvetica", "", 10)
        self.set_text_color(*MUTED)
        self.cell(self.usable, 6, "", align="L")
        self.set_x(MARGIN)
        self.cell(self.usable, 0, self.doc_number, align="R", new_x="LMARGIN", new_y="NEXT")
        self.ln(4)
        self.set_draw_color(*RULE)
        self.line(MARGIN, self.get_y(), self.w - MARGIN, self.get_y())
        self.ln(5)

    def footer(self) -> None:  # fpdf hook
        self.set_y(-16)
        self.set_draw_color(*RULE)
        self.line(MARGIN, self.get_y(), self.w - MARGIN, self.get_y())
        self.set_y(-13)
        self.set_font("helvetica", "", 8)
        self.set_text_color(*MUTED)
        self.cell(
            self.usable / 2, 6, f"{self.doc_number} - generated by Construction ERP", align="L"
        )
        self.cell(self.usable / 2, 6, f"Page {self.page_no()}/{{nb}}", align="R")

    # --- building blocks ------------------------------------------------------

    def meta_grid(self, pairs: list[tuple[str, str]], columns: int = 2) -> None:
        """Key-value pairs laid out in a grid."""
        col_w = self.usable / columns
        for i in range(0, len(pairs), columns):
            row = pairs[i : i + columns]
            for label, _ in row:
                self.set_font("helvetica", "", 8)
                self.set_text_color(*MUTED)
                self.cell(col_w, 4.5, label.upper(), align="L")
            self.ln(4.5)
            for _, value in row:
                self.set_font("helvetica", "B", 10.5)
                self.set_text_color(*INK)
                self.cell(col_w, 6, value, align="L")
            self.ln(8)
        self.ln(2)

    def section_title(self, title: str) -> None:
        self.set_font("helvetica", "B", 10)
        self.set_text_color(*BRAND)
        self.cell(self.usable, 7, title.upper(), new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def table(
        self,
        cols: list[Col],
        rows: list[list[str]],
        totals: list[str] | None = None,
    ) -> None:
        widths = [c.width * self.usable for c in cols]
        # header
        self.set_fill_color(*BRAND)
        self.set_text_color(255, 255, 255)
        self.set_font("helvetica", "B", 8.5)
        for col, width in zip(cols, widths, strict=True):
            self.cell(width, 7, f" {col.label}", align=col.align, fill=True)
        self.ln(7)
        # body
        self.set_font("helvetica", "", 9.5)
        for i, row in enumerate(rows):
            fill = i % 2 == 1
            if fill:
                self.set_fill_color(*ZEBRA)
            self.set_text_color(*INK)
            tallest = 6.5
            for value, col, width in zip(row, cols, widths, strict=True):
                text = _latin(str(value))
                # truncate over-long cells rather than wrapping (keeps rows even)
                while self.get_string_width(text) > width - 3 and len(text) > 4:
                    text = text[:-2]
                self.cell(width, tallest, f" {text}", align=col.align, fill=fill)
            self.ln(tallest)
        # totals band
        if totals:
            self.set_draw_color(*BRAND)
            self.set_line_width(0.4)
            self.line(MARGIN, self.get_y(), self.w - MARGIN, self.get_y())
            self.set_line_width(0.2)
            self.set_font("helvetica", "B", 9.5)
            self.set_text_color(*INK)
            for value, col, width in zip(totals, cols, widths, strict=True):
                self.cell(width, 8, f" {value}", align=col.align)
            self.ln(10)
        else:
            self.ln(3)

    def amount_summary(self, pairs: list[tuple[str, str]], highlight_last: bool = True) -> None:
        """Right-aligned money summary block (gross / retention / net ...)."""
        label_w, value_w = self.usable * 0.55, self.usable * 0.45
        for i, (label, value) in enumerate(pairs):
            last = highlight_last and i == len(pairs) - 1
            if last:
                self.set_fill_color(*BRAND)
                self.set_text_color(255, 255, 255)
                self.set_font("helvetica", "B", 11)
                self.cell(label_w, 9, f" {label}", fill=True)
                self.cell(value_w, 9, f"{value} ", align="R", fill=True)
                self.ln(9)
            else:
                self.set_text_color(*MUTED)
                self.set_font("helvetica", "", 10)
                self.cell(label_w, 7, f" {label}")
                self.set_text_color(*INK)
                self.set_font("helvetica", "B", 10)
                self.cell(value_w, 7, f"{value} ", align="R")
                self.ln(7)
        self.ln(3)

    def note(self, text: str) -> None:
        self.set_font("helvetica", "", 9)
        self.set_text_color(*MUTED)
        self.multi_cell(self.usable, 5, text)
        self.ln(2)

    def render(self) -> bytes:
        return bytes(self.output())
