/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountingRouteImport } from './routes/_app/accounting'
import { Route as AppAssistantRouteImport } from './routes/_app/assistant'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppFieldRouteImport } from './routes/_app/field'
import { Route as AppFleetRouteImport } from './routes/_app/fleet'
import { Route as AppMapRouteImport } from './routes/_app/map'
import { Route as AppWorkloadRouteImport } from './routes/_app/workload'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as PortalTokenRouteImport } from './routes/portal/$token'
import { Route as RfqTokenRouteImport } from './routes/rfq/$token'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppClientsClientIdRouteImport } from './routes/_app/clients/$clientId'
import { Route as AppExpensesIndexRouteImport } from './routes/_app/expenses/index'
import { Route as AppExpensesClaimIdRouteImport } from './routes/_app/expenses/$claimId'
import { Route as AppFleetEquipmentIdRouteImport } from './routes/_app/fleet.$equipmentId'
import { Route as AppInboxIndexRouteImport } from './routes/_app/inbox/index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory/index'
import { Route as AppInventoryItemIdRouteImport } from './routes/_app/inventory/$itemId'
import { Route as AppInventoryInsightsRouteImport } from './routes/_app/inventory/insights'
import { Route as AppInventoryStocktakeRouteImport } from './routes/_app/inventory/stocktake'
import { Route as AppPayrollIndexRouteImport } from './routes/_app/payroll/index'
import { Route as AppProcurementIndexRouteImport } from './routes/_app/procurement/index'
import { Route as AppProcurementRequisitionsRouteImport } from './routes/_app/procurement/requisitions'
import { Route as AppProcurementSuppliersRouteImport } from './routes/_app/procurement/suppliers'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app/tasks.$taskId'
import { Route as AppValuationsValuationIdRouteImport } from './routes/_app/valuations/$valuationId'
import { Route as AppInventoryStocktakeStocktakeIdRouteImport } from './routes/_app/inventory/stocktake.$stocktakeId'
import { Route as AppPayrollRunsRunIdRouteImport } from './routes/_app/payroll/runs.$runId'
import { Route as AppPayrollWorkersWorkerIdRouteImport } from './routes/_app/payroll/workers.$workerId'
import { Route as AppProcurementPosPoIdRouteImport } from './routes/_app/procurement/pos.$poId'
import { Route as AppProcurementRequisitionsRequisitionIdRouteImport } from './routes/_app/procurement/requisitions.$requisitionId'
import { Route as AppProcurementRfqsRfqIdRouteImport } from './routes/_app/procurement/rfqs.$rfqId'
import { Route as AppProcurementSuppliersSupplierIdRouteImport } from './routes/_app/procurement/suppliers.$supplierId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId/index'
import { Route as AppProjectsProjectIdBoqRouteImport } from './routes/_app/projects/$projectId/boq'
import { Route as AppProjectsProjectIdDocumentsRouteImport } from './routes/_app/projects/$projectId/documents'
import { Route as AppProjectsProjectIdProcurementRouteImport } from './routes/_app/projects/$projectId/procurement'
import { Route as AppProjectsProjectIdProgramRouteImport } from './routes/_app/projects/$projectId/program'
import { Route as AppProjectsProjectIdSiteRouteImport } from './routes/_app/projects/$projectId/site'
import { Route as AppProjectsProjectIdSubcontractsRouteImport } from './routes/_app/projects/$projectId/subcontracts'
import { Route as AppProjectsProjectIdTasksRouteImport } from './routes/_app/projects/$projectId/tasks'
import { Route as AppProjectsProjectIdValuationsRouteImport } from './routes/_app/projects/$projectId/valuations'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppFieldRoute = AppFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetRoute = AppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkloadRoute = AppWorkloadRouteImport.update({
  id: '/workload',
  path: '/workload',
  getParentRoute: () => AppRoute,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqTokenRoute = RfqTokenRouteImport.update({
  id: '/rfq/$token',
  path: '/rfq/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesClaimIdRoute = AppExpensesClaimIdRouteImport.update({
  id: '/expenses/$claimId',
  path: '/expenses/$claimId',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetEquipmentIdRoute = AppFleetEquipmentIdRouteImport.update({
  id: '/$equipmentId',
  path: '/$equipmentId',
  getParentRoute: () => AppFleetRoute,
} as any)
const AppInboxIndexRoute = AppInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryItemIdRoute = AppInventoryItemIdRouteImport.update({
  id: '/inventory/$itemId',
  path: '/inventory/$itemId',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryInsightsRoute = AppInventoryInsightsRouteImport.update({
  id: '/inventory/insights',
  path: '/inventory/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryStocktakeRoute = AppInventoryStocktakeRouteImport.update({
  id: '/inventory/stocktake',
  path: '/inventory/stocktake',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollIndexRoute = AppPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementIndexRoute = AppProcurementIndexRouteImport.update({
  id: '/procurement/',
  path: '/procurement/',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRequisitionsRoute =
  AppProcurementRequisitionsRouteImport.update({
    id: '/procurement/requisitions',
    path: '/procurement/requisitions',
    getParentRoute: () => AppRoute,
  } as any)
const AppProcurementSuppliersRoute = AppProcurementSuppliersRouteImport.update({
  id: '/procurement/suppliers',
  path: '/procurement/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const AppValuationsValuationIdRoute =
  AppValuationsValuationIdRouteImport.update({
    id: '/valuations/$valuationId',
    path: '/valuations/$valuationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryStocktakeStocktakeIdRoute =
  AppInventoryStocktakeStocktakeIdRouteImport.update({
    id: '/$stocktakeId',
    path: '/$stocktakeId',
    getParentRoute: () => AppInventoryStocktakeRoute,
  } as any)
const AppPayrollRunsRunIdRoute = AppPayrollRunsRunIdRouteImport.update({
  id: '/payroll/runs/$runId',
  path: '/payroll/runs/$runId',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollWorkersWorkerIdRoute =
  AppPayrollWorkersWorkerIdRouteImport.update({
    id: '/payroll/workers/$workerId',
    path: '/payroll/workers/$workerId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProcurementPosPoIdRoute = AppProcurementPosPoIdRouteImport.update({
  id: '/procurement/pos/$poId',
  path: '/procurement/pos/$poId',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRequisitionsRequisitionIdRoute =
  AppProcurementRequisitionsRequisitionIdRouteImport.update({
    id: '/$requisitionId',
    path: '/$requisitionId',
    getParentRoute: () => AppProcurementRequisitionsRoute,
  } as any)
const AppProcurementRfqsRfqIdRoute = AppProcurementRfqsRfqIdRouteImport.update({
  id: '/procurement/rfqs/$rfqId',
  path: '/procurement/rfqs/$rfqId',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementSuppliersSupplierIdRoute =
  AppProcurementSuppliersSupplierIdRouteImport.update({
    id: '/$supplierId',
    path: '/$supplierId',
    getParentRoute: () => AppProcurementSuppliersRoute,
  } as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdBoqRoute = AppProjectsProjectIdBoqRouteImport.update({
  id: '/boq',
  path: '/boq',
  getParentRoute: () => AppProjectsProjectIdRoute,
} as any)
const AppProjectsProjectIdDocumentsRoute =
  AppProjectsProjectIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdProcurementRoute =
  AppProjectsProjectIdProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdProgramRoute =
  AppProjectsProjectIdProgramRouteImport.update({
    id: '/program',
    path: '/program',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdSiteRoute =
  AppProjectsProjectIdSiteRouteImport.update({
    id: '/site',
    path: '/site',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdSubcontractsRoute =
  AppProjectsProjectIdSubcontractsRouteImport.update({
    id: '/subcontracts',
    path: '/subcontracts',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdTasksRoute =
  AppProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdValuationsRoute =
  AppProjectsProjectIdValuationsRouteImport.update({
    id: '/valuations',
    path: '/valuations',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/accounting': typeof AppAccountingRoute
  '/assistant': typeof AppAssistantRoute
  '/calendar': typeof AppCalendarRoute
  '/field': typeof AppFieldRoute
  '/fleet': typeof AppFleetRouteWithChildren
  '/map': typeof AppMapRoute
  '/workload': typeof AppWorkloadRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/portal/$token': typeof PortalTokenRoute
  '/rfq/$token': typeof RfqTokenRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/expenses/$claimId': typeof AppExpensesClaimIdRoute
  '/fleet/$equipmentId': typeof AppFleetEquipmentIdRoute
  '/inventory/$itemId': typeof AppInventoryItemIdRoute
  '/inventory/insights': typeof AppInventoryInsightsRoute
  '/inventory/stocktake': typeof AppInventoryStocktakeRouteWithChildren
  '/procurement/requisitions': typeof AppProcurementRequisitionsRouteWithChildren
  '/procurement/suppliers': typeof AppProcurementSuppliersRouteWithChildren
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/valuations/$valuationId': typeof AppValuationsValuationIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/clients/': typeof AppClientsIndexRoute
  '/expenses/': typeof AppExpensesIndexRoute
  '/inbox/': typeof AppInboxIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/payroll/': typeof AppPayrollIndexRoute
  '/procurement/': typeof AppProcurementIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/inventory/stocktake/$stocktakeId': typeof AppInventoryStocktakeStocktakeIdRoute
  '/payroll/runs/$runId': typeof AppPayrollRunsRunIdRoute
  '/payroll/workers/$workerId': typeof AppPayrollWorkersWorkerIdRoute
  '/procurement/pos/$poId': typeof AppProcurementPosPoIdRoute
  '/procurement/requisitions/$requisitionId': typeof AppProcurementRequisitionsRequisitionIdRoute
  '/procurement/rfqs/$rfqId': typeof AppProcurementRfqsRfqIdRoute
  '/procurement/suppliers/$supplierId': typeof AppProcurementSuppliersSupplierIdRoute
  '/projects/$projectId/boq': typeof AppProjectsProjectIdBoqRoute
  '/projects/$projectId/documents': typeof AppProjectsProjectIdDocumentsRoute
  '/projects/$projectId/procurement': typeof AppProjectsProjectIdProcurementRoute
  '/projects/$projectId/program': typeof AppProjectsProjectIdProgramRoute
  '/projects/$projectId/site': typeof AppProjectsProjectIdSiteRoute
  '/projects/$projectId/subcontracts': typeof AppProjectsProjectIdSubcontractsRoute
  '/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/projects/$projectId/valuations': typeof AppProjectsProjectIdValuationsRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/accounting': typeof AppAccountingRoute
  '/assistant': typeof AppAssistantRoute
  '/calendar': typeof AppCalendarRoute
  '/field': typeof AppFieldRoute
  '/fleet': typeof AppFleetRouteWithChildren
  '/map': typeof AppMapRoute
  '/workload': typeof AppWorkloadRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/portal/$token': typeof PortalTokenRoute
  '/rfq/$token': typeof RfqTokenRoute
  '/': typeof AppIndexRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/expenses/$claimId': typeof AppExpensesClaimIdRoute
  '/fleet/$equipmentId': typeof AppFleetEquipmentIdRoute
  '/inventory/$itemId': typeof AppInventoryItemIdRoute
  '/inventory/insights': typeof AppInventoryInsightsRoute
  '/inventory/stocktake': typeof AppInventoryStocktakeRouteWithChildren
  '/procurement/requisitions': typeof AppProcurementRequisitionsRouteWithChildren
  '/procurement/suppliers': typeof AppProcurementSuppliersRouteWithChildren
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/valuations/$valuationId': typeof AppValuationsValuationIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/clients': typeof AppClientsIndexRoute
  '/expenses': typeof AppExpensesIndexRoute
  '/inbox': typeof AppInboxIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/payroll': typeof AppPayrollIndexRoute
  '/procurement': typeof AppProcurementIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/inventory/stocktake/$stocktakeId': typeof AppInventoryStocktakeStocktakeIdRoute
  '/payroll/runs/$runId': typeof AppPayrollRunsRunIdRoute
  '/payroll/workers/$workerId': typeof AppPayrollWorkersWorkerIdRoute
  '/procurement/pos/$poId': typeof AppProcurementPosPoIdRoute
  '/procurement/requisitions/$requisitionId': typeof AppProcurementRequisitionsRequisitionIdRoute
  '/procurement/rfqs/$rfqId': typeof AppProcurementRfqsRfqIdRoute
  '/procurement/suppliers/$supplierId': typeof AppProcurementSuppliersSupplierIdRoute
  '/projects/$projectId/boq': typeof AppProjectsProjectIdBoqRoute
  '/projects/$projectId/documents': typeof AppProjectsProjectIdDocumentsRoute
  '/projects/$projectId/procurement': typeof AppProjectsProjectIdProcurementRoute
  '/projects/$projectId/program': typeof AppProjectsProjectIdProgramRoute
  '/projects/$projectId/site': typeof AppProjectsProjectIdSiteRoute
  '/projects/$projectId/subcontracts': typeof AppProjectsProjectIdSubcontractsRoute
  '/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/projects/$projectId/valuations': typeof AppProjectsProjectIdValuationsRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/accounting': typeof AppAccountingRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/field': typeof AppFieldRoute
  '/_app/fleet': typeof AppFleetRouteWithChildren
  '/_app/map': typeof AppMapRoute
  '/_app/workload': typeof AppWorkloadRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/portal/$token': typeof PortalTokenRoute
  '/rfq/$token': typeof RfqTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clients/$clientId': typeof AppClientsClientIdRoute
  '/_app/expenses/$claimId': typeof AppExpensesClaimIdRoute
  '/_app/fleet/$equipmentId': typeof AppFleetEquipmentIdRoute
  '/_app/inventory/$itemId': typeof AppInventoryItemIdRoute
  '/_app/inventory/insights': typeof AppInventoryInsightsRoute
  '/_app/inventory/stocktake': typeof AppInventoryStocktakeRouteWithChildren
  '/_app/procurement/requisitions': typeof AppProcurementRequisitionsRouteWithChildren
  '/_app/procurement/suppliers': typeof AppProcurementSuppliersRouteWithChildren
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/valuations/$valuationId': typeof AppValuationsValuationIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
  '/_app/inbox/': typeof AppInboxIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/payroll/': typeof AppPayrollIndexRoute
  '/_app/procurement/': typeof AppProcurementIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/inventory/stocktake/$stocktakeId': typeof AppInventoryStocktakeStocktakeIdRoute
  '/_app/payroll/runs/$runId': typeof AppPayrollRunsRunIdRoute
  '/_app/payroll/workers/$workerId': typeof AppPayrollWorkersWorkerIdRoute
  '/_app/procurement/pos/$poId': typeof AppProcurementPosPoIdRoute
  '/_app/procurement/requisitions/$requisitionId': typeof AppProcurementRequisitionsRequisitionIdRoute
  '/_app/procurement/rfqs/$rfqId': typeof AppProcurementRfqsRfqIdRoute
  '/_app/procurement/suppliers/$supplierId': typeof AppProcurementSuppliersSupplierIdRoute
  '/_app/projects/$projectId/boq': typeof AppProjectsProjectIdBoqRoute
  '/_app/projects/$projectId/documents': typeof AppProjectsProjectIdDocumentsRoute
  '/_app/projects/$projectId/procurement': typeof AppProjectsProjectIdProcurementRoute
  '/_app/projects/$projectId/program': typeof AppProjectsProjectIdProgramRoute
  '/_app/projects/$projectId/site': typeof AppProjectsProjectIdSiteRoute
  '/_app/projects/$projectId/subcontracts': typeof AppProjectsProjectIdSubcontractsRoute
  '/_app/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/_app/projects/$projectId/valuations': typeof AppProjectsProjectIdValuationsRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounting'
    | '/assistant'
    | '/calendar'
    | '/field'
    | '/fleet'
    | '/map'
    | '/workload'
    | '/accept-invite/$token'
    | '/portal/$token'
    | '/rfq/$token'
    | '/clients/$clientId'
    | '/expenses/$claimId'
    | '/fleet/$equipmentId'
    | '/inventory/$itemId'
    | '/inventory/insights'
    | '/inventory/stocktake'
    | '/procurement/requisitions'
    | '/procurement/suppliers'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/valuations/$valuationId'
    | '/admin/'
    | '/clients/'
    | '/expenses/'
    | '/inbox/'
    | '/inventory/'
    | '/payroll/'
    | '/procurement/'
    | '/projects/'
    | '/reports/'
    | '/settings/'
    | '/inventory/stocktake/$stocktakeId'
    | '/payroll/runs/$runId'
    | '/payroll/workers/$workerId'
    | '/procurement/pos/$poId'
    | '/procurement/requisitions/$requisitionId'
    | '/procurement/rfqs/$rfqId'
    | '/procurement/suppliers/$supplierId'
    | '/projects/$projectId/boq'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/procurement'
    | '/projects/$projectId/program'
    | '/projects/$projectId/site'
    | '/projects/$projectId/subcontracts'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/valuations'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/accounting'
    | '/assistant'
    | '/calendar'
    | '/field'
    | '/fleet'
    | '/map'
    | '/workload'
    | '/accept-invite/$token'
    | '/portal/$token'
    | '/rfq/$token'
    | '/'
    | '/clients/$clientId'
    | '/expenses/$claimId'
    | '/fleet/$equipmentId'
    | '/inventory/$itemId'
    | '/inventory/insights'
    | '/inventory/stocktake'
    | '/procurement/requisitions'
    | '/procurement/suppliers'
    | '/tasks/$taskId'
    | '/valuations/$valuationId'
    | '/admin'
    | '/clients'
    | '/expenses'
    | '/inbox'
    | '/inventory'
    | '/payroll'
    | '/procurement'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/inventory/stocktake/$stocktakeId'
    | '/payroll/runs/$runId'
    | '/payroll/workers/$workerId'
    | '/procurement/pos/$poId'
    | '/procurement/requisitions/$requisitionId'
    | '/procurement/rfqs/$rfqId'
    | '/procurement/suppliers/$supplierId'
    | '/projects/$projectId/boq'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/procurement'
    | '/projects/$projectId/program'
    | '/projects/$projectId/site'
    | '/projects/$projectId/subcontracts'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/valuations'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/accounting'
    | '/_app/assistant'
    | '/_app/calendar'
    | '/_app/field'
    | '/_app/fleet'
    | '/_app/map'
    | '/_app/workload'
    | '/accept-invite/$token'
    | '/portal/$token'
    | '/rfq/$token'
    | '/_app/'
    | '/_app/clients/$clientId'
    | '/_app/expenses/$claimId'
    | '/_app/fleet/$equipmentId'
    | '/_app/inventory/$itemId'
    | '/_app/inventory/insights'
    | '/_app/inventory/stocktake'
    | '/_app/procurement/requisitions'
    | '/_app/procurement/suppliers'
    | '/_app/projects/$projectId'
    | '/_app/tasks/$taskId'
    | '/_app/valuations/$valuationId'
    | '/_app/admin/'
    | '/_app/clients/'
    | '/_app/expenses/'
    | '/_app/inbox/'
    | '/_app/inventory/'
    | '/_app/payroll/'
    | '/_app/procurement/'
    | '/_app/projects/'
    | '/_app/reports/'
    | '/_app/settings/'
    | '/_app/inventory/stocktake/$stocktakeId'
    | '/_app/payroll/runs/$runId'
    | '/_app/payroll/workers/$workerId'
    | '/_app/procurement/pos/$poId'
    | '/_app/procurement/requisitions/$requisitionId'
    | '/_app/procurement/rfqs/$rfqId'
    | '/_app/procurement/suppliers/$supplierId'
    | '/_app/projects/$projectId/boq'
    | '/_app/projects/$projectId/documents'
    | '/_app/projects/$projectId/procurement'
    | '/_app/projects/$projectId/program'
    | '/_app/projects/$projectId/site'
    | '/_app/projects/$projectId/subcontracts'
    | '/_app/projects/$projectId/tasks'
    | '/_app/projects/$projectId/valuations'
    | '/_app/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  PortalTokenRoute: typeof PortalTokenRoute
  RfqTokenRoute: typeof RfqTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/field': {
      id: '/_app/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof AppFieldRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet': {
      id: '/_app/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AppFleetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workload': {
      id: '/_app/workload'
      path: '/workload'
      fullPath: '/workload'
      preLoaderRoute: typeof AppWorkloadRouteImport
      parentRoute: typeof AppRoute
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq/$token': {
      id: '/rfq/$token'
      path: '/rfq/$token'
      fullPath: '/rfq/$token'
      preLoaderRoute: typeof RfqTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId': {
      id: '/_app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/$claimId': {
      id: '/_app/expenses/$claimId'
      path: '/expenses/$claimId'
      fullPath: '/expenses/$claimId'
      preLoaderRoute: typeof AppExpensesClaimIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet/$equipmentId': {
      id: '/_app/fleet/$equipmentId'
      path: '/$equipmentId'
      fullPath: '/fleet/$equipmentId'
      preLoaderRoute: typeof AppFleetEquipmentIdRouteImport
      parentRoute: typeof AppFleetRoute
    }
    '/_app/inbox/': {
      id: '/_app/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AppInboxIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/$itemId': {
      id: '/_app/inventory/$itemId'
      path: '/inventory/$itemId'
      fullPath: '/inventory/$itemId'
      preLoaderRoute: typeof AppInventoryItemIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/insights': {
      id: '/_app/inventory/insights'
      path: '/inventory/insights'
      fullPath: '/inventory/insights'
      preLoaderRoute: typeof AppInventoryInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/stocktake': {
      id: '/_app/inventory/stocktake'
      path: '/inventory/stocktake'
      fullPath: '/inventory/stocktake'
      preLoaderRoute: typeof AppInventoryStocktakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/': {
      id: '/_app/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof AppPayrollIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement/': {
      id: '/_app/procurement/'
      path: '/procurement'
      fullPath: '/procurement/'
      preLoaderRoute: typeof AppProcurementIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement/requisitions': {
      id: '/_app/procurement/requisitions'
      path: '/procurement/requisitions'
      fullPath: '/procurement/requisitions'
      preLoaderRoute: typeof AppProcurementRequisitionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement/suppliers': {
      id: '/_app/procurement/suppliers'
      path: '/procurement/suppliers'
      fullPath: '/procurement/suppliers'
      preLoaderRoute: typeof AppProcurementSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/valuations/$valuationId': {
      id: '/_app/valuations/$valuationId'
      path: '/valuations/$valuationId'
      fullPath: '/valuations/$valuationId'
      preLoaderRoute: typeof AppValuationsValuationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/stocktake/$stocktakeId': {
      id: '/_app/inventory/stocktake/$stocktakeId'
      path: '/$stocktakeId'
      fullPath: '/inventory/stocktake/$stocktakeId'
      preLoaderRoute: typeof AppInventoryStocktakeStocktakeIdRouteImport
      parentRoute: typeof AppInventoryStocktakeRoute
    }
    '/_app/payroll/runs/$runId': {
      id: '/_app/payroll/runs/$runId'
      path: '/payroll/runs/$runId'
      fullPath: '/payroll/runs/$runId'
      preLoaderRoute: typeof AppPayrollRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/workers/$workerId': {
      id: '/_app/payroll/workers/$workerId'
      path: '/payroll/workers/$workerId'
      fullPath: '/payroll/workers/$workerId'
      preLoaderRoute: typeof AppPayrollWorkersWorkerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement/pos/$poId': {
      id: '/_app/procurement/pos/$poId'
      path: '/procurement/pos/$poId'
      fullPath: '/procurement/pos/$poId'
      preLoaderRoute: typeof AppProcurementPosPoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement/requisitions/$requisitionId': {
      id: '/_app/procurement/requisitions/$requisitionId'
      path: '/$requisitionId'
      fullPath: '/procurement/requisitions/$requisitionId'
      preLoaderRoute: typeof AppProcurementRequisitionsRequisitionIdRouteImport
      parentRoute: typeof AppProcurementRequisitionsRoute
    }
    '/_app/procurement/rfqs/$rfqId': {
      id: '/_app/procurement/rfqs/$rfqId'
      path: '/procurement/rfqs/$rfqId'
      fullPath: '/procurement/rfqs/$rfqId'
      preLoaderRoute: typeof AppProcurementRfqsRfqIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement/suppliers/$supplierId': {
      id: '/_app/procurement/suppliers/$supplierId'
      path: '/$supplierId'
      fullPath: '/procurement/suppliers/$supplierId'
      preLoaderRoute: typeof AppProcurementSuppliersSupplierIdRouteImport
      parentRoute: typeof AppProcurementSuppliersRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/boq': {
      id: '/_app/projects/$projectId/boq'
      path: '/boq'
      fullPath: '/projects/$projectId/boq'
      preLoaderRoute: typeof AppProjectsProjectIdBoqRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/documents': {
      id: '/_app/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof AppProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/procurement': {
      id: '/_app/projects/$projectId/procurement'
      path: '/procurement'
      fullPath: '/projects/$projectId/procurement'
      preLoaderRoute: typeof AppProjectsProjectIdProcurementRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/program': {
      id: '/_app/projects/$projectId/program'
      path: '/program'
      fullPath: '/projects/$projectId/program'
      preLoaderRoute: typeof AppProjectsProjectIdProgramRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/site': {
      id: '/_app/projects/$projectId/site'
      path: '/site'
      fullPath: '/projects/$projectId/site'
      preLoaderRoute: typeof AppProjectsProjectIdSiteRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/subcontracts': {
      id: '/_app/projects/$projectId/subcontracts'
      path: '/subcontracts'
      fullPath: '/projects/$projectId/subcontracts'
      preLoaderRoute: typeof AppProjectsProjectIdSubcontractsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/tasks': {
      id: '/_app/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof AppProjectsProjectIdTasksRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/valuations': {
      id: '/_app/projects/$projectId/valuations'
      path: '/valuations'
      fullPath: '/projects/$projectId/valuations'
      preLoaderRoute: typeof AppProjectsProjectIdValuationsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
  }
}

interface AppFleetRouteChildren {
  AppFleetEquipmentIdRoute: typeof AppFleetEquipmentIdRoute
}

const AppFleetRouteChildren: AppFleetRouteChildren = {
  AppFleetEquipmentIdRoute: AppFleetEquipmentIdRoute,
}

const AppFleetRouteWithChildren = AppFleetRoute._addFileChildren(
  AppFleetRouteChildren,
)

interface AppInventoryStocktakeRouteChildren {
  AppInventoryStocktakeStocktakeIdRoute: typeof AppInventoryStocktakeStocktakeIdRoute
}

const AppInventoryStocktakeRouteChildren: AppInventoryStocktakeRouteChildren = {
  AppInventoryStocktakeStocktakeIdRoute: AppInventoryStocktakeStocktakeIdRoute,
}

const AppInventoryStocktakeRouteWithChildren =
  AppInventoryStocktakeRoute._addFileChildren(
    AppInventoryStocktakeRouteChildren,
  )

interface AppProcurementRequisitionsRouteChildren {
  AppProcurementRequisitionsRequisitionIdRoute: typeof AppProcurementRequisitionsRequisitionIdRoute
}

const AppProcurementRequisitionsRouteChildren: AppProcurementRequisitionsRouteChildren =
  {
    AppProcurementRequisitionsRequisitionIdRoute:
      AppProcurementRequisitionsRequisitionIdRoute,
  }

const AppProcurementRequisitionsRouteWithChildren =
  AppProcurementRequisitionsRoute._addFileChildren(
    AppProcurementRequisitionsRouteChildren,
  )

interface AppProcurementSuppliersRouteChildren {
  AppProcurementSuppliersSupplierIdRoute: typeof AppProcurementSuppliersSupplierIdRoute
}

const AppProcurementSuppliersRouteChildren: AppProcurementSuppliersRouteChildren =
  {
    AppProcurementSuppliersSupplierIdRoute:
      AppProcurementSuppliersSupplierIdRoute,
  }

const AppProcurementSuppliersRouteWithChildren =
  AppProcurementSuppliersRoute._addFileChildren(
    AppProcurementSuppliersRouteChildren,
  )

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdBoqRoute: typeof AppProjectsProjectIdBoqRoute
  AppProjectsProjectIdDocumentsRoute: typeof AppProjectsProjectIdDocumentsRoute
  AppProjectsProjectIdProcurementRoute: typeof AppProjectsProjectIdProcurementRoute
  AppProjectsProjectIdProgramRoute: typeof AppProjectsProjectIdProgramRoute
  AppProjectsProjectIdSiteRoute: typeof AppProjectsProjectIdSiteRoute
  AppProjectsProjectIdSubcontractsRoute: typeof AppProjectsProjectIdSubcontractsRoute
  AppProjectsProjectIdTasksRoute: typeof AppProjectsProjectIdTasksRoute
  AppProjectsProjectIdValuationsRoute: typeof AppProjectsProjectIdValuationsRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdBoqRoute: AppProjectsProjectIdBoqRoute,
  AppProjectsProjectIdDocumentsRoute: AppProjectsProjectIdDocumentsRoute,
  AppProjectsProjectIdProcurementRoute: AppProjectsProjectIdProcurementRoute,
  AppProjectsProjectIdProgramRoute: AppProjectsProjectIdProgramRoute,
  AppProjectsProjectIdSiteRoute: AppProjectsProjectIdSiteRoute,
  AppProjectsProjectIdSubcontractsRoute: AppProjectsProjectIdSubcontractsRoute,
  AppProjectsProjectIdTasksRoute: AppProjectsProjectIdTasksRoute,
  AppProjectsProjectIdValuationsRoute: AppProjectsProjectIdValuationsRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppFieldRoute: typeof AppFieldRoute
  AppFleetRoute: typeof AppFleetRouteWithChildren
  AppMapRoute: typeof AppMapRoute
  AppWorkloadRoute: typeof AppWorkloadRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppExpensesClaimIdRoute: typeof AppExpensesClaimIdRoute
  AppInventoryItemIdRoute: typeof AppInventoryItemIdRoute
  AppInventoryInsightsRoute: typeof AppInventoryInsightsRoute
  AppInventoryStocktakeRoute: typeof AppInventoryStocktakeRouteWithChildren
  AppProcurementRequisitionsRoute: typeof AppProcurementRequisitionsRouteWithChildren
  AppProcurementSuppliersRoute: typeof AppProcurementSuppliersRouteWithChildren
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppValuationsValuationIdRoute: typeof AppValuationsValuationIdRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
  AppInboxIndexRoute: typeof AppInboxIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppPayrollIndexRoute: typeof AppPayrollIndexRoute
  AppProcurementIndexRoute: typeof AppProcurementIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppPayrollRunsRunIdRoute: typeof AppPayrollRunsRunIdRoute
  AppPayrollWorkersWorkerIdRoute: typeof AppPayrollWorkersWorkerIdRoute
  AppProcurementPosPoIdRoute: typeof AppProcurementPosPoIdRoute
  AppProcurementRfqsRfqIdRoute: typeof AppProcurementRfqsRfqIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppFieldRoute: AppFieldRoute,
  AppFleetRoute: AppFleetRouteWithChildren,
  AppMapRoute: AppMapRoute,
  AppWorkloadRoute: AppWorkloadRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppExpensesClaimIdRoute: AppExpensesClaimIdRoute,
  AppInventoryItemIdRoute: AppInventoryItemIdRoute,
  AppInventoryInsightsRoute: AppInventoryInsightsRoute,
  AppInventoryStocktakeRoute: AppInventoryStocktakeRouteWithChildren,
  AppProcurementRequisitionsRoute: AppProcurementRequisitionsRouteWithChildren,
  AppProcurementSuppliersRoute: AppProcurementSuppliersRouteWithChildren,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppValuationsValuationIdRoute: AppValuationsValuationIdRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
  AppInboxIndexRoute: AppInboxIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppPayrollIndexRoute: AppPayrollIndexRoute,
  AppProcurementIndexRoute: AppProcurementIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppPayrollRunsRunIdRoute: AppPayrollRunsRunIdRoute,
  AppPayrollWorkersWorkerIdRoute: AppPayrollWorkersWorkerIdRoute,
  AppProcurementPosPoIdRoute: AppProcurementPosPoIdRoute,
  AppProcurementRfqsRfqIdRoute: AppProcurementRfqsRfqIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  PortalTokenRoute: PortalTokenRoute,
  RfqTokenRoute: RfqTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
