/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppExpensesIndexRouteImport } from './routes/_app/expenses/index'
import { Route as AppInboxIndexRouteImport } from './routes/_app/inbox/index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory/index'
import { Route as AppInventoryItemIdRouteImport } from './routes/_app/inventory/$itemId'
import { Route as AppProcurementIndexRouteImport } from './routes/_app/procurement/index'
import { Route as AppProcurementSuppliersRouteImport } from './routes/_app/procurement/suppliers'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings/users'
import { Route as AppProcurementPosPoIdRouteImport } from './routes/_app/procurement/pos.$poId'
import { Route as AppProcurementRfqsRfqIdRouteImport } from './routes/_app/procurement/rfqs.$rfqId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId/index'
import { Route as AppProjectsProjectIdBoqRouteImport } from './routes/_app/projects/$projectId/boq'
import { Route as AppProjectsProjectIdProcurementRouteImport } from './routes/_app/projects/$projectId/procurement'
import { Route as AppProjectsProjectIdProgramRouteImport } from './routes/_app/projects/$projectId/program'
import { Route as AppProjectsProjectIdSiteRouteImport } from './routes/_app/projects/$projectId/site'
import { Route as AppProjectsProjectIdTasksRouteImport } from './routes/_app/projects/$projectId/tasks'
import { Route as AppProjectsProjectIdValuationsRouteImport } from './routes/_app/projects/$projectId/valuations'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxIndexRoute = AppInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryItemIdRoute = AppInventoryItemIdRouteImport.update({
  id: '/inventory/$itemId',
  path: '/inventory/$itemId',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementIndexRoute = AppProcurementIndexRouteImport.update({
  id: '/procurement/',
  path: '/procurement/',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementSuppliersRoute = AppProcurementSuppliersRouteImport.update({
  id: '/procurement/suppliers',
  path: '/procurement/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementPosPoIdRoute = AppProcurementPosPoIdRouteImport.update({
  id: '/procurement/pos/$poId',
  path: '/procurement/pos/$poId',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRfqsRfqIdRoute = AppProcurementRfqsRfqIdRouteImport.update({
  id: '/procurement/rfqs/$rfqId',
  path: '/procurement/rfqs/$rfqId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdBoqRoute = AppProjectsProjectIdBoqRouteImport.update({
  id: '/boq',
  path: '/boq',
  getParentRoute: () => AppProjectsProjectIdRoute,
} as any)
const AppProjectsProjectIdProcurementRoute =
  AppProjectsProjectIdProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdProgramRoute =
  AppProjectsProjectIdProgramRouteImport.update({
    id: '/program',
    path: '/program',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdSiteRoute =
  AppProjectsProjectIdSiteRouteImport.update({
    id: '/site',
    path: '/site',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdTasksRoute =
  AppProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdValuationsRoute =
  AppProjectsProjectIdValuationsRouteImport.update({
    id: '/valuations',
    path: '/valuations',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/inventory/$itemId': typeof AppInventoryItemIdRoute
  '/procurement/suppliers': typeof AppProcurementSuppliersRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/settings/users': typeof AppSettingsUsersRoute
  '/expenses/': typeof AppExpensesIndexRoute
  '/inbox/': typeof AppInboxIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/procurement/': typeof AppProcurementIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/procurement/pos/$poId': typeof AppProcurementPosPoIdRoute
  '/procurement/rfqs/$rfqId': typeof AppProcurementRfqsRfqIdRoute
  '/projects/$projectId/boq': typeof AppProjectsProjectIdBoqRoute
  '/projects/$projectId/procurement': typeof AppProjectsProjectIdProcurementRoute
  '/projects/$projectId/program': typeof AppProjectsProjectIdProgramRoute
  '/projects/$projectId/site': typeof AppProjectsProjectIdSiteRoute
  '/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/projects/$projectId/valuations': typeof AppProjectsProjectIdValuationsRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/inventory/$itemId': typeof AppInventoryItemIdRoute
  '/procurement/suppliers': typeof AppProcurementSuppliersRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/expenses': typeof AppExpensesIndexRoute
  '/inbox': typeof AppInboxIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/procurement': typeof AppProcurementIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/procurement/pos/$poId': typeof AppProcurementPosPoIdRoute
  '/procurement/rfqs/$rfqId': typeof AppProcurementRfqsRfqIdRoute
  '/projects/$projectId/boq': typeof AppProjectsProjectIdBoqRoute
  '/projects/$projectId/procurement': typeof AppProjectsProjectIdProcurementRoute
  '/projects/$projectId/program': typeof AppProjectsProjectIdProgramRoute
  '/projects/$projectId/site': typeof AppProjectsProjectIdSiteRoute
  '/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/projects/$projectId/valuations': typeof AppProjectsProjectIdValuationsRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/inventory/$itemId': typeof AppInventoryItemIdRoute
  '/_app/procurement/suppliers': typeof AppProcurementSuppliersRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
  '/_app/inbox/': typeof AppInboxIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/procurement/': typeof AppProcurementIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/procurement/pos/$poId': typeof AppProcurementPosPoIdRoute
  '/_app/procurement/rfqs/$rfqId': typeof AppProcurementRfqsRfqIdRoute
  '/_app/projects/$projectId/boq': typeof AppProjectsProjectIdBoqRoute
  '/_app/projects/$projectId/procurement': typeof AppProjectsProjectIdProcurementRoute
  '/_app/projects/$projectId/program': typeof AppProjectsProjectIdProgramRoute
  '/_app/projects/$projectId/site': typeof AppProjectsProjectIdSiteRoute
  '/_app/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/_app/projects/$projectId/valuations': typeof AppProjectsProjectIdValuationsRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/inventory/$itemId'
    | '/procurement/suppliers'
    | '/projects/$projectId'
    | '/settings/users'
    | '/expenses/'
    | '/inbox/'
    | '/inventory/'
    | '/procurement/'
    | '/projects/'
    | '/reports/'
    | '/procurement/pos/$poId'
    | '/procurement/rfqs/$rfqId'
    | '/projects/$projectId/boq'
    | '/projects/$projectId/procurement'
    | '/projects/$projectId/program'
    | '/projects/$projectId/site'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/valuations'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/inventory/$itemId'
    | '/procurement/suppliers'
    | '/settings/users'
    | '/expenses'
    | '/inbox'
    | '/inventory'
    | '/procurement'
    | '/projects'
    | '/reports'
    | '/procurement/pos/$poId'
    | '/procurement/rfqs/$rfqId'
    | '/projects/$projectId/boq'
    | '/projects/$projectId/procurement'
    | '/projects/$projectId/program'
    | '/projects/$projectId/site'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/valuations'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/inventory/$itemId'
    | '/_app/procurement/suppliers'
    | '/_app/projects/$projectId'
    | '/_app/settings/users'
    | '/_app/expenses/'
    | '/_app/inbox/'
    | '/_app/inventory/'
    | '/_app/procurement/'
    | '/_app/projects/'
    | '/_app/reports/'
    | '/_app/procurement/pos/$poId'
    | '/_app/procurement/rfqs/$rfqId'
    | '/_app/projects/$projectId/boq'
    | '/_app/projects/$projectId/procurement'
    | '/_app/projects/$projectId/program'
    | '/_app/projects/$projectId/site'
    | '/_app/projects/$projectId/tasks'
    | '/_app/projects/$projectId/valuations'
    | '/_app/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox/': {
      id: '/_app/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AppInboxIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/$itemId': {
      id: '/_app/inventory/$itemId'
      path: '/inventory/$itemId'
      fullPath: '/inventory/$itemId'
      preLoaderRoute: typeof AppInventoryItemIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement/': {
      id: '/_app/procurement/'
      path: '/procurement'
      fullPath: '/procurement/'
      preLoaderRoute: typeof AppProcurementIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement/suppliers': {
      id: '/_app/procurement/suppliers'
      path: '/procurement/suppliers'
      fullPath: '/procurement/suppliers'
      preLoaderRoute: typeof AppProcurementSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement/pos/$poId': {
      id: '/_app/procurement/pos/$poId'
      path: '/procurement/pos/$poId'
      fullPath: '/procurement/pos/$poId'
      preLoaderRoute: typeof AppProcurementPosPoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement/rfqs/$rfqId': {
      id: '/_app/procurement/rfqs/$rfqId'
      path: '/procurement/rfqs/$rfqId'
      fullPath: '/procurement/rfqs/$rfqId'
      preLoaderRoute: typeof AppProcurementRfqsRfqIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/boq': {
      id: '/_app/projects/$projectId/boq'
      path: '/boq'
      fullPath: '/projects/$projectId/boq'
      preLoaderRoute: typeof AppProjectsProjectIdBoqRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/procurement': {
      id: '/_app/projects/$projectId/procurement'
      path: '/procurement'
      fullPath: '/projects/$projectId/procurement'
      preLoaderRoute: typeof AppProjectsProjectIdProcurementRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/program': {
      id: '/_app/projects/$projectId/program'
      path: '/program'
      fullPath: '/projects/$projectId/program'
      preLoaderRoute: typeof AppProjectsProjectIdProgramRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/site': {
      id: '/_app/projects/$projectId/site'
      path: '/site'
      fullPath: '/projects/$projectId/site'
      preLoaderRoute: typeof AppProjectsProjectIdSiteRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/tasks': {
      id: '/_app/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof AppProjectsProjectIdTasksRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/valuations': {
      id: '/_app/projects/$projectId/valuations'
      path: '/valuations'
      fullPath: '/projects/$projectId/valuations'
      preLoaderRoute: typeof AppProjectsProjectIdValuationsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
  }
}

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdBoqRoute: typeof AppProjectsProjectIdBoqRoute
  AppProjectsProjectIdProcurementRoute: typeof AppProjectsProjectIdProcurementRoute
  AppProjectsProjectIdProgramRoute: typeof AppProjectsProjectIdProgramRoute
  AppProjectsProjectIdSiteRoute: typeof AppProjectsProjectIdSiteRoute
  AppProjectsProjectIdTasksRoute: typeof AppProjectsProjectIdTasksRoute
  AppProjectsProjectIdValuationsRoute: typeof AppProjectsProjectIdValuationsRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdBoqRoute: AppProjectsProjectIdBoqRoute,
  AppProjectsProjectIdProcurementRoute: AppProjectsProjectIdProcurementRoute,
  AppProjectsProjectIdProgramRoute: AppProjectsProjectIdProgramRoute,
  AppProjectsProjectIdSiteRoute: AppProjectsProjectIdSiteRoute,
  AppProjectsProjectIdTasksRoute: AppProjectsProjectIdTasksRoute,
  AppProjectsProjectIdValuationsRoute: AppProjectsProjectIdValuationsRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppInventoryItemIdRoute: typeof AppInventoryItemIdRoute
  AppProcurementSuppliersRoute: typeof AppProcurementSuppliersRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
  AppInboxIndexRoute: typeof AppInboxIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppProcurementIndexRoute: typeof AppProcurementIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppProcurementPosPoIdRoute: typeof AppProcurementPosPoIdRoute
  AppProcurementRfqsRfqIdRoute: typeof AppProcurementRfqsRfqIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppInventoryItemIdRoute: AppInventoryItemIdRoute,
  AppProcurementSuppliersRoute: AppProcurementSuppliersRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
  AppInboxIndexRoute: AppInboxIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppProcurementIndexRoute: AppProcurementIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppProcurementPosPoIdRoute: AppProcurementPosPoIdRoute,
  AppProcurementRfqsRfqIdRoute: AppProcurementRfqsRfqIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
