# Import every module's models so Base.metadata (and Alembic autogenerate) sees all tables.
from app.modules.accounting import models as accounting_models  # noqa: F401
from app.modules.admin import models as admin_models  # noqa: F401
from app.modules.boq import models as boq_models  # noqa: F401
from app.modules.clients import models as clients_models  # noqa: F401
from app.modules.comments import models as comments_models  # noqa: F401
from app.modules.company import models as company_models  # noqa: F401
from app.modules.costs import models as costs_models  # noqa: F401
from app.modules.expenses import models as expenses_models  # noqa: F401
from app.modules.ingestion import models as ingestion_models  # noqa: F401
from app.modules.inventory import models as inventory_models  # noqa: F401
from app.modules.media import models as media_models  # noqa: F401
from app.modules.notifications import models as notifications_models  # noqa: F401
from app.modules.payroll import models as payroll_models  # noqa: F401
from app.modules.portal import models as portal_models  # noqa: F401
from app.modules.procurement import models as procurement_models  # noqa: F401
from app.modules.requisitions import models as requisitions_models  # noqa: F401
from app.modules.projects import models as projects_models  # noqa: F401
from app.modules.site import models as site_models  # noqa: F401
from app.modules.tasks import models as tasks_models  # noqa: F401
from app.modules.users import models as users_models  # noqa: F401
from app.modules.valuations import models as valuations_models  # noqa: F401
